//-----------------------------------------------------------------------
// <copyright file="AdvancedFilterType.cs" company="Ace Poker Solutions">
// Copyright © 2018 Ace Poker Solutions. All Rights Reserved.
// Unless otherwise noted, all materials contained in this Site are copyrights, 
// trademarks, trade dress and/or other intellectual properties, owned, 
// controlled or licensed by Ace Poker Solutions and may not be used without 
// written consent except as provided in these terms and conditions or in the 
// copyright notice (documents and software) or other proprietary notices 
// provided with the relevant materials.
// </copyright>
//----------------------------------------------------------------------

namespace Model.Filters
{
    public enum AdvancedFilterType
    {
        // PREFLOP
        VPIP = 0,
        PutMoneyinPot = 1,
        PFR = 2,
        PFRFalse = 302,
        Did3Bet = 3,
        DidSqueeze = 4,
        DidColdCall = 5,
        CouldColdCall = 303,
        CouldColdCallFalse = 304,
        FacedPreflop3Bet = 6,
        FoldedToPreflop3Bet = 7,
        CalledPreflop3Bet = 8,
        RaisedPreflop3Bet = 9,
        FacedPreflop4Bet = 10,
        FoldedToPreflop4Bet = 11,
        CalledPreflop4Bbet = 12,
        RaisedPreflop4Bet = 13,
        InBBandStealAttempted = 14,
        InBBandStealDefended = 15,
        InBBandStealReraised = 16,
        InSBandStealAttempted = 17,
        InSBandStealDefended = 18,
        InSBandStealReraised = 19,
        LimpReraised = 20,
        BBsBetPreflopisBiggerThan = 21,
        BBsBetPreflopisLessThan = 22,
        BBsCalledPreflopisBiggerThan = 23,
        BBsCalledPreflopisLessThan = 24,
        BBsPutInPreflopisBiggerThan = 25,
        BBsPutInPreflopisLessThan = 26,
        PreflopRaiseSizePotisBiggerThan = 27,
        PreflopRaiseSizePotisLessThan = 28,
        PreflopFacingRaiseSizePotisBiggerThan = 29,
        PreflopFacingRaiseSizePotisLessThan = 30,
        AllinPreflop = 31,

        // FLOP
        SawFlop = 32,
        SawFlopFalse = 308,
        LasttoActionFlop = 33,
        LasttoActionFlopFalse = 305,
        FlopUnopened = 34,
        PlayersonFlopisBiggerThan = 35,
        PlayersonFlopisLessThan = 36,
        PlayersonFlopisEqualTo = 37,
        FlopContinuationBetPossible = 38,
        FlopContinuationBetMade = 39,
        FacingFlopContinuationBet = 40,
        FoldedtoFlopContinuationBet = 41,
        CalledFlopContinuationBet = 42,
        RaisedFlopContinuationBet = 43,
        FlopBet = 44,
        FlopBetFold = 45,
        FlopBetCall = 46,
        FlopBetRaise = 47,
        FlopRaise = 48,
        FlopRaiseFold = 49,
        FlopRaiseCall = 50,
        FlopRaiseRaise = 51,
        FlopCall = 52,
        FlopCallFold = 53,
        FlopCallCall = 54,
        FlopCallRaise = 55,
        FlopCheck = 56,
        FlopCheckFold = 57,
        FlopCheckCall = 58,
        FlopCheckRaise = 59,
        FlopFold = 60,
        FlopWasCheckRaised = 61,
        FlopWasBetInto = 62,
        FlopWasRaised = 63,
        BBsBetFlopisBiggerThan = 64,
        BBsBetFlopisLessThan = 65,
        BBsCalledFlopisBiggerThan = 66,
        BBsCalledFlopisLessThan = 67,
        BBsPutinFlopisBiggerThan = 68,
        BBsPutinFlopisLessThan = 69,
        FlopPotSizeinBBsisBiggerThan = 70,
        FlopPotSizeinBBsisLessThan = 71,
        FlopStackPotRatioisBiggerThan = 72,
        FlopStackPotRatioisLessThan = 73,
        FlopBetSizePotisBiggerThan = 74,
        FlopBetSizePotisLessThan = 75,
        FlopRaiseSizePotisBiggerThan = 76,
        FlopRaiseSizePotisLessThan = 77,
        FlopFacingBetSizePotisBiggerThan = 78,
        FlopFacingBetSizePotisLessThan = 79,
        FlopFacingRaiseSizePotisBiggerThan = 80,
        FlopFacingRaiseSizePotisLessThan = 81,
        AllinOnFlop = 82,
        AllinOnFlopOrEarlier = 83,

        // TURN
        SawTurn = 84,
        LasttoActonTurn = 85,
        LasttoActonTurnFalse = 306,
        TurnUnopened = 86,
        TurnUnopenedFalse = 300,
        PlayersonTurnisBiggerThan = 87,
        PlayersonTurnisLessThan = 88,
        PlayersonTurnisEqualTo = 89,
        TurnContinuationBetPossible = 90,
        TurnContinuationBetMade = 91,
        FacingTurnContinuationBet = 92,
        FoldedtoTurnContinuationBet = 93,
        CalledTurnContinuationBet = 94,
        RaisedTurnContinuationBet = 95,
        TurnBet = 96,
        TurnBetFold = 97,
        TurnBetCall = 98,
        TurnBetRaise = 99,
        TurnRaise = 100,
        TurnRaiseFold = 101,
        TurnRaiseCall = 102,
        TurnRaiseRaise = 103,
        TurnCall = 104,
        TurnCallFold = 105,
        TurnCallCall = 106,
        TurnCallRaise = 107,
        TurnCheck = 108,
        TurnCheckFold = 109,
        TurnCheckCall = 110,
        TurnCheckRaise = 111,
        TurnFold = 112,
        TurnWasCheckRaised = 113,
        TurnWasBetInto = 114,
        TurnWasRaised = 115,
        BBsBetTurnisBiggerThan = 116,
        BBsBetTurnisLessThan = 117,
        BBsCalledTurnisBiggerThan = 118,
        BBsCalledTurnisLessThan = 119,
        BBsPutinTurnisBiggerThan = 120,
        BBsPutinTurnisLessThan = 121,
        TurnPotSizeinBBsisBiggerThan = 123,
        TurnPotSizeinBBsisLessThan = 124,
        TurnStackPotRatioisBiggerThan = 125,
        TurnStackPotRatioisLessThan = 126,
        TurnBetSizePotisBiggerThan = 127,
        TurnBetSizePotisLessThan = 128,
        TurnRaiseSizePotisBiggerThan = 129,
        TurnRaiseSizePotisLessThan = 130,
        TurnFacingBetSizePotisBiggerThan = 131,
        TurnFacingBetSizePotisLessThan = 132,
        TurnFacingRaiseSizePotisBiggerThan = 133,
        TurnFacingRaiseSizePotisLessThan = 134,
        AllinonTurn = 135,
        AllinonTurnOrEarlier = 136,

        // RIVER
        SawRiver = 137,
        LasttoActonRiver = 138,
        LasttoActonRiverFalse = 307,
        RiverUnopened = 139,
        RiverUnopenedFalse = 301,
        PlayersonRiverisBiggerThan = 140,
        PlayersonRiverisLessThan = 141,
        PlayersonRiverisEqualTo = 142,
        RiverContinuationBetPossible = 143,
        RiverContinuationBetMade = 144,
        FacingRiverContinuationBet = 145,
        FoldedtoRiverContinuationBet = 146,
        CalledRiverContinuationBet = 147,
        RaisedRiverContinuationBet = 148,
        RiverBet = 149,
        RiverBetFold = 150,
        RiverBetCall = 151,
        RiverBetRaise = 152,
        RiverRaise = 153,
        RiverRaiseFold = 154,
        RiverRaiseCall = 155,
        RiverRaiseRaise = 156,
        RiverCall = 157,
        RiverCallFold = 158,
        RiverCallCall = 159,
        RiverCallRaise = 160,
        RiverCheck = 161,
        RiverCheckFold = 162,
        RiverCheckCall = 163,
        RiverCheckRaise = 164,
        RiverFold = 165,
        RiverWasCheckRaised = 166,
        RiverWasBetInto = 167,
        RiverWasRaised = 168,
        BBsBetRiverisBiggerThan = 169,
        BBsBetRiverisLessThan = 170,
        BBsCalledRiverisBiggerThan = 171,
        BBsCalledRiverisLessThan = 172,
        BBsPutinRiverisBiggerThan = 173,
        BBsPutinRiverisLessThan = 174,
        RiverPotSizeinBBsisBiggerThan = 175,
        RiverPotSizeinBBsisLessThan = 176,
        RiverStackPotRatioisBiggerThan = 177,
        RiverStackPotRatioisLessThan = 178,
        RiverBetSizePotisBiggerThan = 179,
        RiverBetSizePotisLessThan = 180,
        RiverRaiseSizePotisBiggerThan = 181,
        RiverRaiseSizePotisLessThan = 182,
        RiverFacingBetSizePotisBiggerThan = 183,
        RiverFacingBetSizePotisLessThan = 184,
        RiverFacingRaiseSizePotisBiggerThan = 185,
        RiverFacingRaiseSizePotisLessThan = 186,

        // OTHER
        SawShowdown = 187,
        WonHand = 188,
        FinalPotSizeinBBsisBiggerThan = 189,
        FinalPotSizeinBBsisLessThan = 190,
        PlayerWonBBsIsBiggerThan = 191,
        PlayerWonBBsIsLessThan = 192,
        PlayerLostBBsIsBiggerThan = 193,
        PlayerLostBBsIsLessThan = 194,
        PlayerWonOrLostBBsIsBiggerThan = 195,
        PlayerWonOrLostBBsIsLessThan = 196,
        PlayersSawShowdownIsBiggerThan = 197,
        PlayersSawShowdownIsLessThan = 198,
        PlayersSawShowdownIsEqualTo = 199,
        AllinWinIsBiggerThan = 200,
        AllinWinIsLessThan = 201
    }
}