//-----------------------------------------------------------------------
// <copyright file="PlayerstatisticMap.cs" company="Ace Poker Solutions">
// Copyright © 2015 Ace Poker Solutions. All Rights Reserved.
// Unless otherwise noted, all materials contained in this Site are copyrights, 
// trademarks, trade dress and/or other intellectual properties, owned, 
// controlled or licensed by Ace Poker Solutions and may not be used without 
// written consent except as provided in these terms and conditions or in the 
// copyright notice (documents and software) or other proprietary notices 
// provided with the relevant materials.
// </copyright>
//----------------------------------------------------------------------

using FluentNHibernate.Mapping;

namespace DriveHUD.Entities.Mapping
{
    public partial class PlayerstatisticMap : ClassMap<Playerstatistic>
    {
        public PlayerstatisticMap()
        {
            Table("PlayerStatistic");
            LazyLoad();
            Id(x => x.CompiledplayerresultsId).GeneratedBy.Native().Column("PlayerStatisticId").Not.Nullable();
            Map(x => x.PlayerId).Column("PlayerId").Not.Nullable();
            Map(x => x.GametypeId).Column("GametypeId").Not.Nullable();
            Map(x => x.Time).Column("Timestamp").Not.Nullable();
            Map(x => x.Numberofplayers).Column("Numberofplayers").Not.Nullable();
            Map(x => x.PokergametypeId).Column("PokergametypeId").Not.Nullable();
            Map(x => x.Wonhand).Column("Wonhand").Nullable();
            Map(x => x.Totalpostflopstreetsplayed).Column("Totalpostflopstreetsplayed").Nullable();
            Map(x => x.Bigblindstealdefended).Column("Bigblindstealdefended").Nullable();
            Map(x => x.Calledthreebetpreflop).Column("Calledthreebetpreflop").Nullable();
            Map(x => x.Turnfoldippassonflopcb).Column("Turnfoldippassonflopcb").Nullable();
            Map(x => x.Rivercallippassonturncb).Column("Rivercallippassonturncb").Nullable();
            Map(x => x.Turncontinuationbetmade).Column("Turncontinuationbetmade").Nullable();
            Map(x => x.Wonhandwhensawturn).Column("Wonhandwhensawturn").Nullable();
            Map(x => x.Turncontinuationbetpossible).Column("Turncontinuationbetpossible").Nullable();
            Map(x => x.Couldcoldcall).Column("Couldcoldcall").Nullable();
            Map(x => x.Totalamountwonincents).Column("Totalamountwonincents").Nullable();
            Map(x => x.Facedfourbetpreflop).Column("Facedfourbetpreflop").Nullable();
            Map(x => x.Flopcontinuationbetpossible).Column("Flopcontinuationbetpossible").Nullable();
            Map(x => x.Riverfoldippassonturncb).Column("Riverfoldippassonturncb").Nullable();
            Map(x => x.Facingturncontinuationbet).Column("Facingturncontinuationbet").Nullable();
            Map(x => x.Sawlargeshowdown).Column("Sawlargeshowdown").Nullable();
            Map(x => x.Raisedthreebetpreflop).Column("Raisedthreebetpreflop").Nullable();
            Map(x => x.Vpiphands).Column("Vpiphands").Nullable();
            Map(x => x.Facingrivercontinuationbet).Column("Facingrivercontinuationbet").Nullable();
            Map(x => x.Wonnonsmallshowdown).Column("Wonnonsmallshowdown").Nullable();
            Map(x => x.Totalbets).Column("Totalbets").Nullable();
            Map(x => x.Riverraiseippassonturncb).Column("Riverraiseippassonturncb").Nullable();
            Map(x => x.Pfrhands).Column("Pfrhands").Nullable();
            Map(x => x.Smallblindstealdefended).Column("Smallblindstealdefended").Nullable();
            Map(x => x.Wonhandwhensawriver).Column("Wonhandwhensawriver").Nullable();
            Map(x => x.Foldedtoflopcontinuationbet).Column("Foldedtoflopcontinuationbet").Nullable();
            Map(x => x.Wonnonsmallshowdownlimpedflop).Column("Wonnonsmallshowdownlimpedflop").Nullable();
            Map(x => x.Calledfourbetpreflop).Column("Calledfourbetpreflop").Nullable();
            Map(x => x.Rivercontinuationbetmade).Column("Rivercontinuationbetmade").Nullable();
            Map(x => x.Calledturncontinuationbet).Column("Calledturncontinuationbet").Nullable();
            Map(x => x.Bigblindstealreraised).Column("Bigblindstealreraised").Nullable();
            Map(x => x.Totalcalls).Column("Totalcalls").Nullable();
            Map(x => x.Sawshowdown).Column("Sawshowdown").Nullable();
            Map(x => x.Calledflopcontinuationbet).Column("Calledflopcontinuationbet").Nullable();
            Map(x => x.Bigblindstealfaced).Column("Bigblindstealfaced").Nullable();
            Map(x => x.Turnraiseippassonflopcb).Column("Turnraiseippassonflopcb").Nullable();
            Map(x => x.Turncallippassonflopcb).Column("Turncallippassonflopcb").Nullable();
            Map(x => x.Wonlargeshowdown).Column("Wonlargeshowdown").Nullable();
            Map(x => x.Couldthreebet).Column("Couldthreebet").Nullable();
            Map(x => x.Smallblindstealfaced).Column("Smallblindstealfaced").Nullable();
            Map(x => x.Sawnonsmallshowdown).Column("Sawnonsmallshowdown").Nullable();
            Map(x => x.Foldedtothreebetpreflop).Column("Foldedtothreebetpreflop").Nullable();
            Map(x => x.Foldedtorivercontinuationbet).Column("Foldedtorivercontinuationbet").Nullable();
            Map(x => x.Raisedturncontinuationbet).Column("Raisedturncontinuationbet").Nullable();
            Map(x => x.Smallblindstealreraised).Column("Smallblindstealreraised").Nullable();
            Map(x => x.Wonshowdown).Column("Wonshowdown").Nullable();
            Map(x => x.Raisedflopcontinuationbet).Column("Raisedflopcontinuationbet").Nullable();
            Map(x => x.Wonhandwhensawflop).Column("Wonhandwhensawflop").Nullable();
            Map(x => x.Flopcontinuationbetmade).Column("Flopcontinuationbetmade").Nullable();
            Map(x => x.Foldedtoturncontinuationbet).Column("Foldedtoturncontinuationbet").Nullable();
            Map(x => x.Calledtwopreflopraisers).Column("Calledtwopreflopraisers").Nullable();
            Map(x => x.Raisedtwopreflopraisers).Column("Raisedtwopreflopraisers").Nullable();
            Map(x => x.Totalbbswon).Column("Totalbbswon").Nullable();
            Map(x => x.Totalrakeincents).Column("Totalrakeincents").Nullable();
            Map(x => x.Couldsqueeze).Column("Couldsqueeze").Nullable();
            Map(x => x.Foldedtofourbetpreflop).Column("Foldedtofourbetpreflop").Nullable();
            Map(x => x.Totalhands).Column("Totalhands").Nullable();
            Map(x => x.Facedthreebetpreflop).Column("Facedthreebetpreflop").Nullable();
            Map(x => x.Facingflopcontinuationbet).Column("Facingflopcontinuationbet").Nullable();
            Map(x => x.Rivercontinuationbetpossible).Column("Rivercontinuationbetpossible").Nullable();
            Map(x => x.Didcoldcall).Column("Didcoldcall").Nullable();
            Map(x => x.Wonlargeshowdownlimpedflop).Column("Wonlargeshowdownlimpedflop").Nullable();
            Map(x => x.Sawflop).Column("Sawflop").Nullable();
            Map(x => x.Totalaggressivepostflopstreetsseen).Column("Totalaggressivepostflopstreetsseen").Nullable();
            Map(x => x.Didthreebet).Column("Didthreebet").Nullable();
            Map(x => x.Raisedfourbetpreflop).Column("Raisedfourbetpreflop").Nullable();
            Map(x => x.Sawlargeshowdownlimpedflop).Column("Sawlargeshowdownlimpedflop").Nullable();
            Map(x => x.Raisedrivercontinuationbet).Column("Raisedrivercontinuationbet").Nullable();
            Map(x => x.Facingtwopreflopraisers).Column("Facingtwopreflopraisers").Nullable();
            Map(x => x.Sawnonsmallshowdownlimpedflop).Column("Sawnonsmallshowdownlimpedflop").Nullable();
            Map(x => x.Didsqueeze).Column("Didsqueeze").Nullable();
            Map(x => x.Calledrivercontinuationbet).Column("Calledrivercontinuationbet").Nullable();
            Map(x => x.IsSmallBlind).Column("IsSmallBlind").Nullable();
            Map(x => x.IsBigBlind).Column("IsBigBlind").Nullable();
            Map(x => x.IsDealer).Column("IsDealer").Nullable();
            Map(x => x.IsCutoff).Column("IsCutoff").Nullable();
            Map(x => x.PositionString).Column("PositionString").Nullable();
            Map(x => x.Cards).Column("Cards").Nullable();
            Map(x => x.Line).Column("Line").Nullable();
            Map(x => x.Board).Column("Board").Nullable();
            Map(x => x.FacingPreflop).Column("FacingPreflop").Nullable();
            Map(x => x.Action).Column("Action").Nullable();
            Map(x => x.Allin).Column("Allin").Nullable();
            Map(x => x.Equity).Column("Equity").Nullable();
            Map(x => x.EquityDiff).Column("EquityDiff").Nullable();
            Map(x => x.GameType).Column("GameType").Nullable();
            Map(x => x.Stakes).Column("Stakes").Nullable();
            Map(x => x.SawUnopenedPot).Column("SawUnopenedPot").Nullable();
            Map(x => x.UO_PFR_EP).Column("UO_PFR_EP").Nullable();
            Map(x => x.UO_PFR_MP).Column("UO_PFR_MP").Nullable();
            Map(x => x.UO_PFR_CO).Column("UO_PFR_CO").Nullable();
            Map(x => x.UO_PFR_BN).Column("UO_PFR_BN").Nullable();
            Map(x => x.UO_PFR_SB).Column("UO_PFR_SB").Nullable();
            Map(x => x.UO_PFR_BB).Column("UO_PFR_BB").Nullable();
            Map(x => x.FirstRaiser).Column("FirstRaiser").Nullable();
            Map(x => x.StealPossible).Column("StealPossible").Nullable();
            Map(x => x.StealMade).Column("StealMade").Nullable();
            Map(x => x.Couldfourbet).Column("Couldfourbet").Nullable();
            Map(x => x.Didfourbet).Column("Didfourbet").Nullable();
            Map(x => x.Bigblindstealfolded).Column("Bigblindstealfolded").Nullable();
            Map(x => x.Smallblindstealfolded).Column("Smallblindstealfolded").Nullable();
            Map(x => x.GameNumber).Column("GameNumber").Nullable();
            Map(x => x.Pot).Column("Pot").Nullable();
            Map(x => x.IsTourney).Column("IsTourney").Nullable();
            Map(x => x.TournamentId).Column("TournamentId").Nullable();
            Map(x => x.TableType).Column("TableType").Nullable();
            Map(x => x.SmallBlind).Column("SmallBlind").Nullable();
            Map(x => x.BigBlind).Column("BigBlind").Nullable();
            Map(x => x.StartingStack).Column("StartingStack").Nullable();
            Map(x => x.Ante).Column("Ante").Nullable();
            Map(x => x.SawTurn).Column("SawTurn").Nullable();
            Map(x => x.SawRiver).Column("SawRiver").Nullable();
            Map(x => x.DidOpenRaise).Column("DidOpenRaise").Nullable();
            Map(x => x.DidCheckRaise).Column("DidCheckRaise").Nullable();
            Map(x => x.IsRelativePosition).Column("IsRelativePosition").Nullable();
            Map(x => x.IsRaisedLimpers).Column("IsRaisedLimpers").Nullable();
            Map(x => x.IsRelative3BetPosition).Column("IsRelative3BetPosition").Nullable();
            Map(x => x.CurrencyId).Column("CurrencyId").Nullable();
            Map(x => x.Position).Column("Position").Nullable();
            Map(x => x.DidThreeBetInMp).Column("DidThreeBetInMp").Nullable();
            Map(x => x.DidThreeBetInCo).Column("DidThreeBetInCo").Nullable();
            Map(x => x.DidThreeBetInBtn).Column("DidThreeBetInBtn").Nullable();
            Map(x => x.DidThreeBetInSb).Column("DidThreeBetInSb").Nullable();
            Map(x => x.DidThreeBetInBb).Column("DidThreeBetInBb").Nullable();
            Map(x => x.DidFourBetInMp).Column("DidFourBetInMp").Nullable();
            Map(x => x.DidFourBetInCo).Column("DidFourBetInCo").Nullable();
            Map(x => x.DidFourBetInBtn).Column("DidFourBetInBtn").Nullable();
            Map(x => x.DidFourBetInSb).Column("DidFourBetInSb").Nullable();
            Map(x => x.DidFourBetInBb).Column("DidFourBetInBb").Nullable();
            Map(x => x.DidColdCallInMp).Column("DidColdCallInMp").Nullable();
            Map(x => x.DidColdCallInCo).Column("DidColdCallInCo").Nullable();
            Map(x => x.DidColdCallInBtn).Column("DidColdCallInBtn").Nullable();
            Map(x => x.DidColdCallInSb).Column("DidColdCallInSb").Nullable();
            Map(x => x.DidColdCallInBb).Column("DidColdCallInBb").Nullable();
            Map(x => x.DidDonkBet).Column("DidDonkBet").Nullable();
            Map(x => x.CouldDonkBet).Column("CouldDonkBet").Nullable();
            Map(x => x.DidDelayedTurnCBet).Column("DidDelayedTurnCBet").Nullable();
            Map(x => x.CouldDelayedTurnCBet).Column("CouldDelayedTurnCBet").Nullable();
            Map(x => x.DidFlopCheckRaise).Column("DidFlopCheckRaise").Nullable();
            Map(x => x.DidTurnCheckRaise).Column("DidTurnCheckRaise").Nullable();
            Map(x => x.DidRiverCheckRaise).Column("DidRiverCheckRaise").Nullable();
            Map(x => x.PlayedFloatFlop).Column("PlayedFloatFlop").Nullable();
            Map(x => x.CouldRaiseFlop).Column("CouldRaiseFlop").Nullable();
            Map(x => x.CouldRaiseTurn).Column("CouldRaiseTurn").Nullable();
            Map(x => x.CouldRaiseRiver).Column("CouldRaiseRiver").Nullable();
            Map(x => x.TurnContinuationBetWithAirMade).Column("TurnContinuationBetWithAirMade").Nullable();
            Map(x => x.WasFlop).Column("WasFlop").Nullable();
            Map(x => x.WasTurn).Column("WasTurn").Nullable();
            Map(x => x.WasRiver).Column("WasRiver").Nullable();
            Map(x => x.DidRaiseFlop).Column("DidRaiseFlop").Nullable();
            Map(x => x.DidRaiseTurn).Column("DidRaiseTurn").Nullable();
            Map(x => x.DidRaiseRiver).Column("DidRaiseRiver").Nullable();
            Map(x => x.CouldThreeBetVsSteal).Column("CouldThreeBetVsSteal").Nullable();
            Map(x => x.DidThreeBetVsSteal).Column("DidThreeBetVsSteal").Nullable();
            Map(x => x.CouldCheckRiverOnBXLine).Column("CouldCheckRiverOnBXLine").Nullable();
            Map(x => x.DidCheckRiverOnBXLine).Column("DidCheckRiverOnBXLine").Nullable();
            Map(x => x.TotalAggressiveBets).Column("TotalAggressiveBets").Nullable();
            Map(x => x.DidColdCallIp).Column("DidColdCallIp").Nullable();
            Map(x => x.DidColdCallOop).Column("DidColdCallOop").Nullable();
            Map(x => x.DidthreebetBluffInSb).Column("DidthreebetBluffInSb").Nullable();
            Map(x => x.DidthreebetBluffInBb).Column("DidthreebetBluffInBb").Nullable();
            Map(x => x.DidthreebetBluffInBlinds).Column("DidthreebetBluffInBlinds").Nullable();
            Map(x => x.DidfourbetBluff).Column("DidfourbetBluff").Nullable();
            Map(x => x.DidFourBetBluffInBtn).Column("DidFourBetBluffInBtn").Nullable();
            Map(x => x.DidBluffedRiver).Column("DidBluffedRiver").Nullable();
            Map(x => x.BlindsStealDefended).Column("BlindsStealDefended").Nullable();
            Map(x => x.DidCheckFlop).Column("DidCheckFlop").Nullable();
            Map(x => x.FacedHandsUpOnFlop).Column("FacedHandsUpOnFlop").Nullable();
            Map(x => x.FacedMultiWayOnFlop).Column("FacedMultiWayOnFlop").Nullable();
            Map(x => x.SessionCode).Column("SessionCode").Nullable();
            Map(x => x.LimpPossible).Column("LimpPossible").Nullable();
            Map(x => x.LimpMade).Column("LimpMade").Nullable();
            Map(x => x.LimpFaced).Column("LimpFaced").Nullable();
            Map(x => x.LimpCalled).Column("LimpCalled").Nullable();
            Map(x => x.LimpFolded).Column("LimpFolded").Nullable();
            Map(x => x.LimpReraised).Column("LimpReraised").Nullable();
            Map(x => x.MRatio).Column("MRatio").Nullable();
            Map(x => x.StackInBBs).Column("StackInBBs").Nullable();
            Map(x => x.TotalbetsFlop).Column("TotalbetsFlop").Nullable();
            Map(x => x.TotalbetsTurn).Column("TotalbetsTurn").Nullable();
            Map(x => x.TotalbetsRiver).Column("TotalbetsRiver").Nullable();
            Map(x => x.TotalcallsFlop).Column("TotalcallsFlop").Nullable();
            Map(x => x.TotalcallsTurn).Column("TotalcallsTurn").Nullable();
            Map(x => x.TotalcallsRiver).Column("TotalcallsRiver").Nullable();
            Map(x => x.FlopAggPossible).Column("FlopAggPossible").Nullable();
            Map(x => x.TurnAggPossible).Column("TurnAggPossible").Nullable();
            Map(x => x.RiverAggPossible).Column("RiverAggPossible").Nullable();
            Map(x => x.Smallblindstealattempted).Column("Smallblindstealattempted").Nullable();
            Map(x => x.FlopContinuationBetInThreeBetPotPossible).Column("FlopContinuationBetInThreeBetPotPossible").Nullable();
            Map(x => x.FlopContinuationBetInThreeBetPotMade).Column("FlopContinuationBetInThreeBetPotMade").Nullable();
            Map(x => x.FlopContinuationBetInFourBetPotPossible).Column("FlopContinuationBetInFourBetPotPossible").Nullable();
            Map(x => x.FlopContinuationBetInFourBetPotMade).Column("FlopContinuationBetInFourBetPotMade").Nullable();
            Map(x => x.FlopContinuationBetVsOneOpponentPossible).Column("FlopContinuationBetVsOneOpponentPossible").Nullable();
            Map(x => x.FlopContinuationBetVsOneOpponentMade).Column("FlopContinuationBetVsOneOpponentMade").Nullable();
            Map(x => x.FlopContinuationBetVsTwoOpponentsPossible).Column("FlopContinuationBetVsTwoOpponentsPossible").Nullable();
            Map(x => x.FlopContinuationBetVsTwoOpponentsMade).Column("FlopContinuationBetVsTwoOpponentsMade").Nullable();
            Map(x => x.MultiWayFlopContinuationBetPossible).Column("MultiWayFlopContinuationBetPossible").Nullable();
            Map(x => x.MultiWayFlopContinuationBetMade).Column("MultiWayFlopContinuationBetMade").Nullable();
            Map(x => x.FlopContinuationBetMonotonePotPossible).Column("FlopContinuationBetMonotonePotPossible").Nullable();
            Map(x => x.FlopContinuationBetMonotonePotMade).Column("FlopContinuationBetMonotonePotMade").Nullable();
            Map(x => x.FlopContinuationBetRagPotPossible).Column("FlopContinuationBetRagPotPossible").Nullable();
            Map(x => x.FlopContinuationBetRagPotMade).Column("FlopContinuationBetRagPotMade").Nullable();
            Map(x => x.FacingFlopContinuationBetFromThreeBetPot).Column("FacingFlopContinuationBetFromThreeBetPot").Nullable();
            Map(x => x.FoldedToFlopContinuationBetFromThreeBetPot).Column("FoldedToFlopContinuationBetFromThreeBetPot").Nullable();
            Map(x => x.CalledFlopContinuationBetFromThreeBetPot).Column("CalledFlopContinuationBetFromThreeBetPot").Nullable();
            Map(x => x.RaisedFlopContinuationBetFromThreeBetPot).Column("RaisedFlopContinuationBetFromThreeBetPot").Nullable();
            Map(x => x.FacingFlopContinuationBetFromFourBetPot).Column("FacingFlopContinuationBetFromFourBetPot").Nullable();
            Map(x => x.FoldedToFlopContinuationBetFromFourBetPot).Column("FoldedToFlopContinuationBetFromFourBetPot").Nullable();
            Map(x => x.CalledFlopContinuationBetFromFourBetPot).Column("CalledFlopContinuationBetFromFourBetPot").Nullable();
            Map(x => x.RaisedFlopContinuationBetFromFourBetPot).Column("RaisedFlopContinuationBetFromFourBetPot").Nullable();
            Map(x => x.DidThreeBetIp).Column("DidThreeBetIp").Nullable();
            Map(x => x.CouldThreeBetIp).Column("CouldThreeBetIp").Nullable();
            Map(x => x.DidThreeBetOop).Column("DidThreeBetOop").Nullable();
            Map(x => x.CouldThreeBetOop).Column("CouldThreeBetOop").Nullable();
            Map(x => x.Flopcontinuationipbetmade).Column("Flopcontinuationipbetmade").Nullable();
            Map(x => x.Flopcontinuationipbetpossible).Column("Flopcontinuationipbetpossible").Nullable();
            Map(x => x.Flopcontinuationoopbetmade).Column("Flopcontinuationoopbetmade").Nullable();
            Map(x => x.Flopcontinuationoopbetpossible).Column("Flopcontinuationoopbetpossible").Nullable();
        }
    }
}