//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveHUD.PlayerXRay.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveHUD.PlayerXRay.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drivehud.com/product/player-xray.
        /// </summary>
        internal static string XRay_BuyLink {
            get {
                return ResourceManager.GetString("XRay_BuyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string XRay_RegistrationView_Back {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string XRay_RegistrationView_Buy {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string XRay_RegistrationView_Cancel {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s) left:.
        /// </summary>
        internal static string XRay_RegistrationView_DaysLeft {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string XRay_RegistrationView_Email {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Player X-Ray - An automated note taking application that will allow you to see right through your opponents strategies in order to make the best possible adjustments to their game. No need to write tedious notes while multi-tabling online. Sit back and allow Play X-Ray to do all of the hard work and make the essential reads you might be missing otherwise..
        /// </summary>
        internal static string XRay_RegistrationView_GreetingText {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string XRay_RegistrationView_OK {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string XRay_RegistrationView_Register {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the following data to register your version of Player X-Ray:.
        /// </summary>
        internal static string XRay_RegistrationView_RegisterText {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        internal static string XRay_RegistrationView_Renew {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial:.
        /// </summary>
        internal static string XRay_RegistrationView_Serial {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you. Player X-Ray has been successfully registered!.
        /// </summary>
        internal static string XRay_RegistrationView_Success {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text on picture:.
        /// </summary>
        internal static string XRay_RegistrationView_TextOnPicture {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_TextOnPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player X-Ray Registration.
        /// </summary>
        internal static string XRay_RegistrationView_Title {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        internal static string XRay_RegistrationView_Trial {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the following data to activate your trial period:.
        /// </summary>
        internal static string XRay_RegistrationView_TrialRegisterText {
            get {
                return ResourceManager.GetString("XRay_RegistrationView_TrialRegisterText", resourceCulture);
            }
        }
    }
}
