//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveHUD.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveHUD.Common.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3Bet.
        /// </summary>
        internal static string Common_3Bet {
            get {
                return ResourceManager.GetString("Common_3Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3Bet / 4Bet.
        /// </summary>
        internal static string Common_3Bet4Bet {
            get {
                return ResourceManager.GetString("Common_3Bet4Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4Bet.
        /// </summary>
        internal static string Common_4Bet {
            get {
                return ResourceManager.GetString("Common_4Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5Bet.
        /// </summary>
        internal static string Common_5Bet {
            get {
                return ResourceManager.GetString("Common_5Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string Common_Alias {
            get {
                return ResourceManager.GetString("Common_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players: {0}.
        /// </summary>
        internal static string Common_Alias_Players {
            get {
                return ResourceManager.GetString("Common_Alias_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Common_All {
            get {
                return ResourceManager.GetString("Common_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ace Poker Solutions.
        /// </summary>
        internal static string Common_ApplicationCompany {
            get {
                return ResourceManager.GetString("Common_ApplicationCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD - {0} - {1}.
        /// </summary>
        internal static string Common_ApplicationTitle {
            get {
                return ResourceManager.GetString("Common_ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Common_ApplyButtonForCalendars {
            get {
                return ResourceManager.GetString("Common_ApplyButtonForCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Detect.
        /// </summary>
        internal static string Common_AutoDetect {
            get {
                return ResourceManager.GetString("Common_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto generate opponent hand  ranges.
        /// </summary>
        internal static string Common_AutoGenerateHand {
            get {
                return ResourceManager.GetString("Common_AutoGenerateHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet.
        /// </summary>
        internal static string Common_Bet {
            get {
                return ResourceManager.GetString("Common_Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Filter.
        /// </summary>
        internal static string Common_BumperSticker_AddFilter {
            get {
                return ResourceManager.GetString("Common_BumperSticker_AddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Common_BumperSticker_Description {
            get {
                return ResourceManager.GetString("Common_BumperSticker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sticker.
        /// </summary>
        internal static string Common_BumperSticker_EditSticker {
            get {
                return ResourceManager.GetString("Common_BumperSticker_EditSticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sticker.
        /// </summary>
        internal static string Common_BumperSticker_EnableSticker {
            get {
                return ResourceManager.GetString("Common_BumperSticker_EnableSticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker Name.
        /// </summary>
        internal static string Common_BumperSticker_StickerName {
            get {
                return ResourceManager.GetString("Common_BumperSticker_StickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumper Sticker Type.
        /// </summary>
        internal static string Common_BumperSticker_StickerType {
            get {
                return ResourceManager.GetString("Common_BumperSticker_StickerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Color.
        /// </summary>
        internal static string Common_BumperStickers_SelectColor {
            get {
                return ResourceManager.GetString("Common_BumperStickers_SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy-in.
        /// </summary>
        internal static string Common_BuyIn {
            get {
                return ResourceManager.GetString("Common_BuyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drivehud.com/pricing.
        /// </summary>
        internal static string Common_BuyLink {
            get {
                return ResourceManager.GetString("Common_BuyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string Common_Calculate {
            get {
                return ResourceManager.GetString("Common_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Bluff%.
        /// </summary>
        internal static string Common_CalculateBluffPercent {
            get {
                return ResourceManager.GetString("Common_CalculateBluffPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Equity.
        /// </summary>
        internal static string Common_CalculateEquity {
            get {
                return ResourceManager.GetString("Common_CalculateEquity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string Common_Call {
            get {
                return ResourceManager.GetString("Common_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller.
        /// </summary>
        internal static string Common_Caller {
            get {
                return ResourceManager.GetString("Common_Caller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callers.
        /// </summary>
        internal static string Common_Callers {
            get {
                return ResourceManager.GetString("Common_Callers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling  Range.
        /// </summary>
        internal static string Common_CallingRange {
            get {
                return ResourceManager.GetString("Common_CallingRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players that are in the blinds, against an open raise form.
        /// </summary>
        internal static string Common_CallingRange_Blinds {
            get {
                return ResourceManager.GetString("Common_CallingRange_Blinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players that are not in the blinds, against an open raise form.
        /// </summary>
        internal static string Common_CallingRange_NotBlinds {
            get {
                return ResourceManager.GetString("Common_CallingRange_NotBlinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        internal static string Common_Cards {
            get {
                return ResourceManager.GetString("Common_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bb/100.
        /// </summary>
        internal static string Common_Chart_BB100Caption {
            get {
                return ResourceManager.GetString("Common_Chart_BB100Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BB.
        /// </summary>
        internal static string Common_Chart_BBSign {
            get {
                return ResourceManager.GetString("Common_Chart_BBSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string Common_Chart_DollarSign {
            get {
                return ResourceManager.GetString("Common_Chart_DollarSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV.
        /// </summary>
        internal static string Common_Chart_EV {
            get {
                return ResourceManager.GetString("Common_Chart_EV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV.
        /// </summary>
        internal static string Common_Chart_EVSeries {
            get {
                return ResourceManager.GetString("Common_Chart_EVSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands.
        /// </summary>
        internal static string Common_Chart_Hands {
            get {
                return ResourceManager.GetString("Common_Chart_Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Won.
        /// </summary>
        internal static string Common_Chart_MoneyWonCaption {
            get {
                return ResourceManager.GetString("Common_Chart_MoneyWonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Common_Chart_Month {
            get {
                return ResourceManager.GetString("Common_Chart_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Won.
        /// </summary>
        internal static string Common_Chart_NetWonSeries {
            get {
                return ResourceManager.GetString("Common_Chart_NetWonSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to plot.
        /// </summary>
        internal static string Common_Chart_NoData {
            get {
                return ResourceManager.GetString("Common_Chart_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Showdown.
        /// </summary>
        internal static string Common_Chart_NonShowdownSeries {
            get {
                return ResourceManager.GetString("Common_Chart_NonShowdownSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSD.
        /// </summary>
        internal static string Common_Chart_NSD {
            get {
                return ResourceManager.GetString("Common_Chart_NSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD.
        /// </summary>
        internal static string Common_Chart_SD {
            get {
                return ResourceManager.GetString("Common_Chart_SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showdown.
        /// </summary>
        internal static string Common_Chart_ShowdownSeries {
            get {
                return ResourceManager.GetString("Common_Chart_ShowdownSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Common_Chart_TrackBallInfoHeader_Date {
            get {
                return ResourceManager.GetString("Common_Chart_TrackBallInfoHeader_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand:.
        /// </summary>
        internal static string Common_Chart_TrackBallInfoHeader_Hand {
            get {
                return ResourceManager.GetString("Common_Chart_TrackBallInfoHeader_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Common_Chart_Week {
            get {
                return ResourceManager.GetString("Common_Chart_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Common_Chart_Year {
            get {
                return ResourceManager.GetString("Common_Chart_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string Common_Check {
            get {
                return ResourceManager.GetString("Common_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Likelihood.
        /// </summary>
        internal static string Common_CustomLikelihood {
            get {
                return ResourceManager.GetString("Common_CustomLikelihood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was exported and copied to your clipboard. 
        ///Use CTRL+V to paste your exported data..
        /// </summary>
        internal static string Common_DataExported {
            get {
                return ResourceManager.GetString("Common_DataExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Drive HUD.
        /// </summary>
        internal static string Common_DriveHUD {
            get {
                return ResourceManager.GetString("Common_DriveHUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate break even bluff percentage.
        /// </summary>
        internal static string Common_ECBluffPopupCaption {
            get {
                return ResourceManager.GetString("Common_ECBluffPopupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equity Calculator.
        /// </summary>
        internal static string Common_EquityCalculator {
            get {
                return ResourceManager.GetString("Common_EquityCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equity Calculation + Hand History.
        /// </summary>
        internal static string Common_Export_Both {
            get {
                return ResourceManager.GetString("Common_Export_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equity Calculation Only.
        /// </summary>
        internal static string Common_Export_EC {
            get {
                return ResourceManager.GetString("Common_Export_EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand History Only.
        /// </summary>
        internal static string Common_Export_HH {
            get {
                return ResourceManager.GetString("Common_Export_HH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        internal static string Common_ExportData {
            get {
                return ResourceManager.GetString("Common_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Filter.
        /// </summary>
        internal static string Common_FastFilter {
            get {
                return ResourceManager.GetString("Common_FastFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Common_Filters {
            get {
                return ResourceManager.GetString("Common_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop.
        /// </summary>
        internal static string Common_Flop {
            get {
                return ResourceManager.GetString("Common_Flop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold.
        /// </summary>
        internal static string Common_Fold {
            get {
                return ResourceManager.GetString("Common_Fold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Type.
        /// </summary>
        internal static string Common_GameType {
            get {
                return ResourceManager.GetString("Common_GameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs.
        /// </summary>
        internal static string Common_GraphsPopup_Title {
            get {
                return ResourceManager.GetString("Common_GraphsPopup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Common_Help {
            get {
                return ResourceManager.GetString("Common_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holdem.
        /// </summary>
        internal static string Common_Holdem {
            get {
                return ResourceManager.GetString("Common_Holdem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hole Cards.
        /// </summary>
        internal static string Common_HoleCards {
            get {
                return ResourceManager.GetString("Common_HoleCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Stats.
        /// </summary>
        internal static string Common_Hud_AllStats {
            get {
                return ResourceManager.GetString("Common_Hud_AllStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Size to All.
        /// </summary>
        internal static string Common_Hud_ApplySizeToAll {
            get {
                return ResourceManager.GetString("Common_Hud_ApplySizeToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Common_Hud_Copy {
            get {
                return ResourceManager.GetString("Common_Hud_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Common_Hud_Delete {
            get {
                return ResourceManager.GetString("Common_Hud_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string Common_Hud_Duplicate {
            get {
                return ResourceManager.GetString("Common_Hud_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Common_Hud_Export {
            get {
                return ResourceManager.GetString("Common_Hud_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD Name.
        /// </summary>
        internal static string Common_Hud_HudName {
            get {
                return ResourceManager.GetString("Common_Hud_HudName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: This HUD is for Ignition/Bodog only..
        /// </summary>
        internal static string Common_Hud_IgnWarning {
            get {
                return ResourceManager.GetString("Common_Hud_IgnWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Common_Hud_Import {
            get {
                return ResourceManager.GetString("Common_Hud_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Common_Hud_Load {
            get {
                return ResourceManager.GetString("Common_Hud_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Common_Hud_Preview {
            get {
                return ResourceManager.GetString("Common_Hud_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Common_Hud_Save {
            get {
                return ResourceManager.GetString("Common_Hud_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        internal static string Common_Hud_SaveAs {
            get {
                return ResourceManager.GetString("Common_Hud_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Layout.
        /// </summary>
        internal static string Common_Hud_TableLayout {
            get {
                return ResourceManager.GetString("Common_Hud_TableLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Common_Hud_ToolBar_Apply {
            get {
                return ResourceManager.GetString("Common_Hud_ToolBar_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Common_Hud_ToolBar_Delete {
            get {
                return ResourceManager.GetString("Common_Hud_ToolBar_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        internal static string Common_Hud_ToolBar_Rotate {
            get {
                return ResourceManager.GetString("Common_Hud_ToolBar_Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_HudLayout_Cancel {
            get {
                return ResourceManager.GetString("Common_HudLayout_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete HUD layout:.
        /// </summary>
        internal static string Common_HudLayout_DeleteLabel {
            get {
                return ResourceManager.GetString("Common_HudLayout_DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select table type:.
        /// </summary>
        internal static string Common_HudLayout_DuplicateHeader {
            get {
                return ResourceManager.GetString("Common_HudLayout_DuplicateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important! In order to make your new HUD active on your poker table, you&apos;ll need to do the following on your poker site table:.
        /// </summary>
        internal static string Common_HudLayout_FirstSaveNotifyHeader {
            get {
                return ResourceManager.GetString("Common_HudLayout_FirstSaveNotifyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Right click on the DriveHUD logo at the top center of your poker table..
        /// </summary>
        internal static string Common_HudLayout_FirstSaveNotifyP1 {
            get {
                return ResourceManager.GetString("Common_HudLayout_FirstSaveNotifyP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Mouse over to the LOAD HUD from the menu..
        /// </summary>
        internal static string Common_HudLayout_FirstSaveNotifyP2 {
            get {
                return ResourceManager.GetString("Common_HudLayout_FirstSaveNotifyP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Select the HUD you wish to use from the pop out menu and left click to select. The HUD you selected will load on the next hand..
        /// </summary>
        internal static string Common_HudLayout_FirstSaveNotifyP3 {
            get {
                return ResourceManager.GetString("Common_HudLayout_FirstSaveNotifyP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got It!.
        /// </summary>
        internal static string Common_HudLayout_GotIt {
            get {
                return ResourceManager.GetString("Common_HudLayout_GotIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEAT MAP.
        /// </summary>
        internal static string Common_HudLayout_HeatMap {
            get {
                return ResourceManager.GetString("Common_HudLayout_HeatMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter layout&apos;s name:.
        /// </summary>
        internal static string Common_HudLayout_InputLabel {
            get {
                return ResourceManager.GetString("Common_HudLayout_InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_HudLayout_OK {
            get {
                return ResourceManager.GetString("Common_HudLayout_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player range.
        /// </summary>
        internal static string Common_HudLayout_PlayerRange {
            get {
                return ResourceManager.GetString("Common_HudLayout_PlayerRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select HUD layout:.
        /// </summary>
        internal static string Common_HudLayout_SelectLabel {
            get {
                return ResourceManager.GetString("Common_HudLayout_SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Stat.
        /// </summary>
        internal static string Common_HudPlayerType_AddNewStat {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_AddNewStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string Common_HudPlayerType_CreateNew {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Common_HudPlayerType_Delete {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Player Icon.
        /// </summary>
        internal static string Common_HudPlayerType_DisplayPlayerIcon {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_DisplayPlayerIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Player Profile.
        /// </summary>
        internal static string Common_HudPlayerType_EnablePlayerProfile {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_EnablePlayerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Common_HudPlayerType_Export {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All .
        /// </summary>
        internal static string Common_HudPlayerType_ExportAll {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_ExportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string Common_HudPlayerType_High {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Common_HudPlayerType_Import {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import / Export.
        /// </summary>
        internal static string Common_HudPlayerType_ImportExport {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_ImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Common_HudPlayerType_Load {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Common_HudPlayerType_Low {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.Sample.
        /// </summary>
        internal static string Common_HudPlayerType_MinSample {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_MinSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        internal static string Common_HudPlayerType_PlayerName {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Type.
        /// </summary>
        internal static string Common_HudPlayerType_PlayerType {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_PlayerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Common_HudPlayerType_Reset {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset / Delete.
        /// </summary>
        internal static string Common_HudPlayerType_ResetDelete {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_ResetDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Common_HudPlayerType_Save {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats - Edit Player.
        /// </summary>
        internal static string Common_HudPlayerType_StatsEditPlayer {
            get {
                return ResourceManager.GetString("Common_HudPlayerType_StatsEditPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Stat DH Box.
        /// </summary>
        internal static string Common_HudSideBar_4StatDHBoxTool {
            get {
                return ResourceManager.GetString("Common_HudSideBar_4StatDHBoxTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Line.
        /// </summary>
        internal static string Common_HudSideBar_BreakLine {
            get {
                return ResourceManager.GetString("Common_HudSideBar_BreakLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumper Stickers.
        /// </summary>
        internal static string Common_HudSideBar_BumperStickersTool {
            get {
                return ResourceManager.GetString("Common_HudSideBar_BumperStickersTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Bar Graphs.
        /// </summary>
        internal static string Common_HudSideBar_GaugeIndicatorTool {
            get {
                return ResourceManager.GetString("Common_HudSideBar_GaugeIndicatorTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        internal static string Common_HudSideBar_GraphTool {
            get {
                return ResourceManager.GetString("Common_HudSideBar_GraphTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Map.
        /// </summary>
        internal static string Common_HudSideBar_HeatMapTool {
            get {
                return ResourceManager.GetString("Common_HudSideBar_HeatMapTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Stat Box.
        /// </summary>
        internal static string Common_HudSideBar_PlainStatBoxTool {
            get {
                return ResourceManager.GetString("Common_HudSideBar_PlainStatBoxTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Profile Icon.
        /// </summary>
        internal static string Common_HudSideBar_PlayerProfileIconTool {
            get {
                return ResourceManager.GetString("Common_HudSideBar_PlayerProfileIconTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Box.
        /// </summary>
        internal static string Common_HudSideBar_TextBoxTool {
            get {
                return ResourceManager.GetString("Common_HudSideBar_TextBoxTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt Meter.
        /// </summary>
        internal static string Common_HudSideBar_TiltMeterTool {
            get {
                return ResourceManager.GetString("Common_HudSideBar_TiltMeterTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD Design Elements.
        /// </summary>
        internal static string Common_HudSideBar_Title {
            get {
                return ResourceManager.GetString("Common_HudSideBar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_HudStatSettings_Cancel {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color range.
        /// </summary>
        internal static string Common_HudStatSettings_ColorRange {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_ColorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current stat:.
        /// </summary>
        internal static string Common_HudStatSettings_CurrentStat {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_CurrentStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Freshness.
        /// </summary>
        internal static string Common_HudStatSettings_DataFreshness {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_DataFreshness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} days.
        /// </summary>
        internal static string Common_HudStatSettings_DataFreshnessLastDays {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_DataFreshnessLastDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Places.
        /// </summary>
        internal static string Common_HudStatSettings_DecimalPlaces {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_DecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter data for only.
        /// </summary>
        internal static string Common_HudStatSettings_FilterDataForOnly {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_FilterDataForOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Common_HudStatSettings_Font {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD Opacity.
        /// </summary>
        internal static string Common_HudStatSettings_HudOpacity {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_HudOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string Common_HudStatSettings_Label {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of available settings.
        /// </summary>
        internal static string Common_HudStatSettings_ListOfAvailableSettings {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_ListOfAvailableSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.Sample.
        /// </summary>
        internal static string Common_HudStatSettings_MinSample {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_MinSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_HudStatSettings_OK {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Common_HudStatSettings_TableFilterEmptyText {
            get {
                return ResourceManager.GetString("Common_HudStatSettings_TableFilterEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg.Pot Size.
        /// </summary>
        internal static string Common_HudTrackConditions_AveragePotSize {
            get {
                return ResourceManager.GetString("Common_HudTrackConditions_AveragePotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Conditions:.
        /// </summary>
        internal static string Common_HudTrackConditions_TrackConditions {
            get {
                return ResourceManager.GetString("Common_HudTrackConditions_TrackConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limped Pot.
        /// </summary>
        internal static string Common_LimpedPot {
            get {
                return ResourceManager.GetString("Common_LimpedPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limper.
        /// </summary>
        internal static string Common_Limper {
            get {
                return ResourceManager.GetString("Common_Limper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpers.
        /// </summary>
        internal static string Common_Limpers {
            get {
                return ResourceManager.GetString("Common_Limpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PURCHASE.
        /// </summary>
        internal static string Common_Main_Purchase {
            get {
                return ResourceManager.GetString("Common_Main_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Trial).
        /// </summary>
        internal static string Common_Main_Trial {
            get {
                return ResourceManager.GetString("Common_Main_Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPGRADE.
        /// </summary>
        internal static string Common_Main_Upgrade {
            get {
                return ResourceManager.GetString("Common_Main_Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string Common_Main_Version {
            get {
                return ResourceManager.GetString("Common_Main_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Common_Off {
            get {
                return ResourceManager.GetString("Common_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omaha.
        /// </summary>
        internal static string Common_Omaha {
            get {
                return ResourceManager.GetString("Common_Omaha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string Common_On {
            get {
                return ResourceManager.GetString("Common_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Raise.
        /// </summary>
        internal static string Common_OpenRaise {
            get {
                return ResourceManager.GetString("Common_OpenRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string Common_Percentage {
            get {
                return ResourceManager.GetString("Common_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string Common_PercentSign {
            get {
                return ResourceManager.GetString("Common_PercentSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string Common_Place {
            get {
                return ResourceManager.GetString("Common_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Plain HUD.
        /// </summary>
        internal static string Common_PlainHUD {
            get {
                return ResourceManager.GetString("Common_PlainHUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poker Site.
        /// </summary>
        internal static string Common_PokerSite {
            get {
                return ResourceManager.GetString("Common_PokerSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Common_Position {
            get {
                return ResourceManager.GetString("Common_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pot.
        /// </summary>
        internal static string Common_Pot {
            get {
                return ResourceManager.GetString("Common_Pot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Seating.
        /// </summary>
        internal static string Common_Preferred_Seating_Button {
            get {
                return ResourceManager.GetString("Common_Preferred_Seating_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Seating.
        /// </summary>
        internal static string Common_PreferredSeating {
            get {
                return ResourceManager.GetString("Common_PreferredSeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preflop.
        /// </summary>
        internal static string Common_Preflop {
            get {
                return ResourceManager.GetString("Common_Preflop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise.
        /// </summary>
        internal static string Common_Raise {
            get {
                return ResourceManager.GetString("Common_Raise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raiser.
        /// </summary>
        internal static string Common_Raiser {
            get {
                return ResourceManager.GetString("Common_Raiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raisers.
        /// </summary>
        internal static string Common_Raisers {
            get {
                return ResourceManager.GetString("Common_Raisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rake.
        /// </summary>
        internal static string Common_Rake {
            get {
                return ResourceManager.GetString("Common_Rake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string Common_Range {
            get {
                return ResourceManager.GetString("Common_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pairs.
        /// </summary>
        internal static string Common_Ranges_All {
            get {
                return ResourceManager.GetString("Common_Ranges_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt + LeftClick = Add all hands in that row.
        /// </summary>
        internal static string Common_Ranges_AltLeft {
            get {
                return ResourceManager.GetString("Common_Ranges_AltLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + LeftClick = Add all hands in  X and Y rows.
        /// </summary>
        internal static string Common_Ranges_CtrlLeft {
            get {
                return ResourceManager.GetString("Common_Ranges_CtrlLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click = Remove hand.
        /// </summary>
        internal static string Common_Ranges_DoubleClick {
            get {
                return ResourceManager.GetString("Common_Ranges_DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold down mouse = Add multiple hands your mouse over.
        /// </summary>
        internal static string Common_Ranges_HoldDown {
            get {
                return ResourceManager.GetString("Common_Ranges_HoldDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Suited Connectors.
        /// </summary>
        internal static string Common_Ranges_OffSuited {
            get {
                return ResourceManager.GetString("Common_Ranges_OffSuited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Suited 1 Gappers.
        /// </summary>
        internal static string Common_Ranges_OffSuited1Gappers {
            get {
                return ResourceManager.GetString("Common_Ranges_OffSuited1Gappers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-defined Ranges.
        /// </summary>
        internal static string Common_Ranges_Predef {
            get {
                return ResourceManager.GetString("Common_Ranges_Predef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suited Connectors.
        /// </summary>
        internal static string Common_Ranges_Suited {
            get {
                return ResourceManager.GetString("Common_Ranges_Suited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suited 1 Gappers.
        /// </summary>
        internal static string Common_Ranges_Suited1Gappers {
            get {
                return ResourceManager.GetString("Common_Ranges_Suited1Gappers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suits for .
        /// </summary>
        internal static string Common_Ranges_SuitsFor {
            get {
                return ResourceManager.GetString("Common_Ranges_SuitsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 19.5% of range.
        /// </summary>
        internal static string Common_Ranges_Top19_5 {
            get {
                return ResourceManager.GetString("Common_Ranges_Top19_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 4.7% of range.
        /// </summary>
        internal static string Common_Ranges_Top4_7 {
            get {
                return ResourceManager.GetString("Common_Ranges_Top4_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to unselect combo.
        /// </summary>
        internal static string Common_Ranges_Unselect {
            get {
                return ResourceManager.GetString("Common_Ranges_Unselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuy.
        /// </summary>
        internal static string Common_Rebuy {
            get {
                return ResourceManager.GetString("Common_Rebuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Common_RegistrationView_Activate {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Common_RegistrationView_Back {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Common_RegistrationView_Buy {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_RegistrationView_Cancel {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not activate license. Please try again or contact support..
        /// </summary>
        internal static string Common_RegistrationView_CouldNotBeActivated {
            get {
                return ResourceManager.GetString("Common_RegistrationView_CouldNotBeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s) left:.
        /// </summary>
        internal static string Common_RegistrationView_DaysLeft {
            get {
                return ResourceManager.GetString("Common_RegistrationView_DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string Common_RegistrationView_Email {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string Common_RegistrationView_ExpiredSerialSplitter {
            get {
                return ResourceManager.GetString("Common_RegistrationView_ExpiredSerialSplitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license(s) has expired ({0}). Please renew..
        /// </summary>
        internal static string Common_RegistrationView_ExpiredText {
            get {
                return ResourceManager.GetString("Common_RegistrationView_ExpiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} day(s) left.
        /// </summary>
        internal static string Common_RegistrationView_ExpiringLicenseTitle {
            get {
                return ResourceManager.GetString("Common_RegistrationView_ExpiringLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license(s) are expiring soon. Please renew..
        /// </summary>
        internal static string Common_RegistrationView_ExpiringSoonText {
            get {
                return ResourceManager.GetString("Common_RegistrationView_ExpiringSoonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEAUTIFUL - INTUITIVE - POWERFUL
        ///Welcome to DriveHUD - The Next Generation Poker HUD and Database. DriveHUD comes with a fully functional 30 day trial. When you are ready to purchase, you can click BUY from the button below in order to  purchase a registered copy of DriveHUD. When you are ready to register, please click the Register button below..
        /// </summary>
        internal static string Common_RegistrationView_GreetingText {
            get {
                return ResourceManager.GetString("Common_RegistrationView_GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register software. Invalid serial number. Please enter valid serial or contact support..
        /// </summary>
        internal static string Common_RegistrationView_InvalidSerial {
            get {
                return ResourceManager.GetString("Common_RegistrationView_InvalidSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t register software. Unexpected error occured. Please contact support..
        /// </summary>
        internal static string Common_RegistrationView_LicenseError {
            get {
                return ResourceManager.GetString("Common_RegistrationView_LicenseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to license server. Please check your internet connection..
        /// </summary>
        internal static string Common_RegistrationView_NoConnection {
            get {
                return ResourceManager.GetString("Common_RegistrationView_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_RegistrationView_OK {
            get {
                return ResourceManager.GetString("Common_RegistrationView_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Common_RegistrationView_Register {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the following data to register your version of DriveHUD:.
        /// </summary>
        internal static string Common_RegistrationView_RegisterText {
            get {
                return ResourceManager.GetString("Common_RegistrationView_RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        internal static string Common_RegistrationView_Renew {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial:.
        /// </summary>
        internal static string Common_RegistrationView_Serial {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text on picture:.
        /// </summary>
        internal static string Common_RegistrationView_TextOnPicture {
            get {
                return ResourceManager.GetString("Common_RegistrationView_TextOnPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD Registration.
        /// </summary>
        internal static string Common_RegistrationView_Title {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        internal static string Common_RegistrationView_Trial {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You trial period is over. Please register your version of DriveHUD..
        /// </summary>
        internal static string Common_RegistrationView_TrialExpiredText {
            get {
                return ResourceManager.GetString("Common_RegistrationView_TrialExpiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register error. Internal error occurred. Please contact support..
        /// </summary>
        internal static string Common_RegistrationView_TrialRegisterError {
            get {
                return ResourceManager.GetString("Common_RegistrationView_TrialRegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the following data to activate your trial period:.
        /// </summary>
        internal static string Common_RegistrationView_TrialRegisterText {
            get {
                return ResourceManager.GetString("Common_RegistrationView_TrialRegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Common_Remove {
            get {
                return ResourceManager.GetString("Common_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay Hand.
        /// </summary>
        internal static string Common_ReplayHand {
            get {
                return ResourceManager.GetString("Common_ReplayHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All-in Equity%.
        /// </summary>
        internal static string Common_ReportView_Hands_AllInEquity {
            get {
                return ResourceManager.GetString("Common_ReportView_Hands_AllInEquity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        internal static string Common_ReportView_Hands_Board {
            get {
                return ResourceManager.GetString("Common_ReportView_Hands_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        internal static string Common_ReportView_Hands_Cards {
            get {
                return ResourceManager.GetString("Common_ReportView_Hands_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Common_ReportView_Hands_Date {
            get {
                return ResourceManager.GetString("Common_ReportView_Hands_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $EV Diff.
        /// </summary>
        internal static string Common_ReportView_Hands_EvDiff {
            get {
                return ResourceManager.GetString("Common_ReportView_Hands_EvDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Common_ReportView_Hands_Line {
            get {
                return ResourceManager.GetString("Common_ReportView_Hands_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Won.
        /// </summary>
        internal static string Common_ReportView_Hands_NetWon {
            get {
                return ResourceManager.GetString("Common_ReportView_Hands_NetWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Common_ReportView_Hands_Position {
            get {
                return ResourceManager.GetString("Common_ReportView_Hands_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Flop.
        /// </summary>
        internal static string Common_ReportView_Hands_Preflop {
            get {
                return ResourceManager.GetString("Common_ReportView_Hands_Preflop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hole Cards.
        /// </summary>
        internal static string Common_ReportView_ShowHoleCards {
            get {
                return ResourceManager.GetString("Common_ReportView_ShowHoleCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged Hands.
        /// </summary>
        internal static string Common_ReportView_TaggedHands {
            get {
                return ResourceManager.GetString("Common_ReportView_TaggedHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Common_Reset {
            get {
                return ResourceManager.GetString("Common_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        internal static string Common_ResetAll {
            get {
                return ResourceManager.GetString("Common_ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Common_Results {
            get {
                return ResourceManager.GetString("Common_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River.
        /// </summary>
        internal static string Common_River {
            get {
                return ResourceManager.GetString("Common_River", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Common_Select {
            get {
                return ResourceManager.GetString("Common_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        internal static string Common_SelectNone {
            get {
                return ResourceManager.GetString("Common_SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Common_Send {
            get {
                return ResourceManager.GetString("Common_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TO CART.
        /// </summary>
        internal static string Common_Shop_AddToCart {
            get {
                return ResourceManager.GetString("Common_Shop_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Apps.
        /// </summary>
        internal static string Common_Shop_Apps {
            get {
                return ResourceManager.GetString("Common_Shop_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUDs.
        /// </summary>
        internal static string Common_Shop_Huds {
            get {
                return ResourceManager.GetString("Common_Shop_Huds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        internal static string Common_Shop_LearnMore {
            get {
                return ResourceManager.GetString("Common_Shop_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        internal static string Common_Shop_Recommended {
            get {
                return ResourceManager.GetString("Common_Shop_Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Products.
        /// </summary>
        internal static string Common_Shop_Training {
            get {
                return ResourceManager.GetString("Common_Shop_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showdown Hands.
        /// </summary>
        internal static string Common_ShowdownHands {
            get {
                return ResourceManager.GetString("Common_ShowdownHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Common_SiteSetup_Activate {
            get {
                return ResourceManager.GetString("Common_SiteSetup_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Correct.
        /// </summary>
        internal static string Common_SiteSetup_ConfigurationCorrect {
            get {
                return ResourceManager.GetString("Common_SiteSetup_ConfigurationCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Incorrect.
        /// </summary>
        internal static string Common_SiteSetup_ConfigurationIncorrect {
            get {
                return ResourceManager.GetString("Common_SiteSetup_ConfigurationIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string Common_SiteSetup_Deactivate {
            get {
                return ResourceManager.GetString("Common_SiteSetup_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this form again.
        /// </summary>
        internal static string Common_SiteSetup_DoNotShow {
            get {
                return ResourceManager.GetString("Common_SiteSetup_DoNotShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found issues:.
        /// </summary>
        internal static string Common_SiteSetup_FoundIssues {
            get {
                return ResourceManager.GetString("Common_SiteSetup_FoundIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green = Enabled.
        /// </summary>
        internal static string Common_SiteSetup_GreenEnabled {
            get {
                return ResourceManager.GetString("Common_SiteSetup_GreenEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD Site Setup.
        /// </summary>
        internal static string Common_SiteSetup_Header {
            get {
                return ResourceManager.GetString("Common_SiteSetup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {0} online manual.
        /// </summary>
        internal static string Common_SiteSetup_HelpToolTip {
            get {
                return ResourceManager.GetString("Common_SiteSetup_HelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following sites still need setup to be completed, in order for DriveHUD to track hands and display a HUD:.
        /// </summary>
        internal static string Common_SiteSetup_IncofiguredIntroText {
            get {
                return ResourceManager.GetString("Common_SiteSetup_IncofiguredIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD has located the following poker sites installed on your system. Auto import will be enabled by default for them unless you&apos;d prefer to disable them. To disable them click on the activate/deactivate button(s) below and check them as red (disabled)..
        /// </summary>
        internal static string Common_SiteSetup_IntroText {
            get {
                return ResourceManager.GetString("Common_SiteSetup_IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No site detected].
        /// </summary>
        internal static string Common_SiteSetup_NoSiteDetected {
            get {
                return ResourceManager.GetString("Common_SiteSetup_NoSiteDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_SiteSetup_OK {
            get {
                return ResourceManager.GetString("Common_SiteSetup_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red = Disabled.
        /// </summary>
        internal static string Common_SiteSetup_RedDisabled {
            get {
                return ResourceManager.GetString("Common_SiteSetup_RedDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Setup Help.
        /// </summary>
        internal static string Common_SiteSetup_SetupHelpButtonText {
            get {
                return ResourceManager.GetString("Common_SiteSetup_SetupHelpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Site detected].
        /// </summary>
        internal static string Common_SiteSetup_SiteDetected {
            get {
                return ResourceManager.GetString("Common_SiteSetup_SiteDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Common_Speed {
            get {
                return ResourceManager.GetString("Common_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Size.
        /// </summary>
        internal static string Common_StackSize {
            get {
                return ResourceManager.GetString("Common_StackSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string Common_Stats {
            get {
                return ResourceManager.GetString("Common_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Calculation.
        /// </summary>
        internal static string Common_StopCalculation {
            get {
                return ResourceManager.GetString("Common_StopCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        internal static string Common_StoppingCalculation {
            get {
                return ResourceManager.GetString("Common_StoppingCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-max.
        /// </summary>
        internal static string Common_Table6Max {
            get {
                return ResourceManager.GetString("Common_Table6Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Ring.
        /// </summary>
        internal static string Common_TableFullRing {
            get {
                return ResourceManager.GetString("Common_TableFullRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournaments.
        /// </summary>
        internal static string Common_Tournaments {
            get {
                return ResourceManager.GetString("Common_Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament Type.
        /// </summary>
        internal static string Common_TournamentType {
            get {
                return ResourceManager.GetString("Common_TournamentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn.
        /// </summary>
        internal static string Common_Turn {
            get {
                return ResourceManager.GetString("Common_Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unopened.
        /// </summary>
        internal static string Common_Unopened {
            get {
                return ResourceManager.GetString("Common_Unopened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD Updater.
        /// </summary>
        internal static string Common_UpdateCaption {
            get {
                return ResourceManager.GetString("Common_UpdateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is available. Do you want to download it?.
        /// </summary>
        internal static string Common_UpdateQuestion {
            get {
                return ResourceManager.GetString("Common_UpdateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes (v.{0}):.
        /// </summary>
        internal static string Common_UpdateView_ReleaseNotes {
            get {
                return ResourceManager.GetString("Common_UpdateView_ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win%: .
        /// </summary>
        internal static string Common_WinPercent {
            get {
                return ResourceManager.GetString("Common_WinPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won Amount.
        /// </summary>
        internal static string Common_WonAmount {
            get {
                return ResourceManager.GetString("Common_WonAmount", resourceCulture);
            }
        }
    }
}
