//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveHUD.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveHUD.Common.Resources.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash - Holdem.
        /// </summary>
        internal static string Enum_EnumGameType_CashHoldem {
            get {
                return ResourceManager.GetString("Enum_EnumGameType_CashHoldem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash - Omaha.
        /// </summary>
        internal static string Enum_EnumGameType_CashOmaha {
            get {
                return ResourceManager.GetString("Enum_EnumGameType_CashOmaha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTT - Holdem.
        /// </summary>
        internal static string Enum_EnumGameType_MTTHoldem {
            get {
                return ResourceManager.GetString("Enum_EnumGameType_MTTHoldem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTT - Omaha.
        /// </summary>
        internal static string Enum_EnumGameType_MTTOmaha {
            get {
                return ResourceManager.GetString("Enum_EnumGameType_MTTOmaha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNG - Holdem.
        /// </summary>
        internal static string Enum_EnumGameType_SNGHoldem {
            get {
                return ResourceManager.GetString("Enum_EnumGameType_SNGHoldem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNG - Omaha.
        /// </summary>
        internal static string Enum_EnumGameType_SNGOmaha {
            get {
                return ResourceManager.GetString("Enum_EnumGameType_SNGOmaha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmericasCardroom.
        /// </summary>
        internal static string Enum_EnumPokerSites_AmericasCardroom {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_AmericasCardroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BetOnline.
        /// </summary>
        internal static string Enum_EnumPokerSites_BetOnline {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_BetOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlackChipPoker.
        /// </summary>
        internal static string Enum_EnumPokerSites_BlackChipPoker {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_BlackChipPoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodog.
        /// </summary>
        internal static string Enum_EnumPokerSites_Bodog {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_Bodog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bovada/Ignition.
        /// </summary>
        internal static string Enum_EnumPokerSites_Bovada {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_Bovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignition.
        /// </summary>
        internal static string Enum_EnumPokerSites_Ignition {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_Ignition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPoker.
        /// </summary>
        internal static string Enum_EnumPokerSites_IPoker {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_IPoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 888.
        /// </summary>
        internal static string Enum_EnumPokerSites_Poker888 {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_Poker888", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokerStars.
        /// </summary>
        internal static string Enum_EnumPokerSites_PokerStars {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_PokerStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportsBetting.
        /// </summary>
        internal static string Enum_EnumPokerSites_SportsBetting {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_SportsBetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportsBettingAg.
        /// </summary>
        internal static string Enum_EnumPokerSites_SportsBettingAg {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_SportsBettingAg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TigerGaming.
        /// </summary>
        internal static string Enum_EnumPokerSites_TigerGaming {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_TigerGaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Poker.
        /// </summary>
        internal static string Enum_EnumPokerSites_TruePoker {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_TruePoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YaPoker.
        /// </summary>
        internal static string Enum_EnumPokerSites_YaPoker {
            get {
                return ResourceManager.GetString("Enum_EnumPokerSites_YaPoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than.
        /// </summary>
        internal static string Enum_EnumStatInfoValueRangeType_LessThan {
            get {
                return ResourceManager.GetString("Enum_EnumStatInfoValueRangeType_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Than.
        /// </summary>
        internal static string Enum_EnumStatInfoValueRangeType_MoreThan {
            get {
                return ResourceManager.GetString("Enum_EnumStatInfoValueRangeType_MoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-max.
        /// </summary>
        internal static string Enum_EnumTableType_Eight {
            get {
                return ResourceManager.GetString("Enum_EnumTableType_Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-max.
        /// </summary>
        internal static string Enum_EnumTableType_Five {
            get {
                return ResourceManager.GetString("Enum_EnumTableType_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-max.
        /// </summary>
        internal static string Enum_EnumTableType_Four {
            get {
                return ResourceManager.GetString("Enum_EnumTableType_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-max.
        /// </summary>
        internal static string Enum_EnumTableType_HU {
            get {
                return ResourceManager.GetString("Enum_EnumTableType_HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9-max.
        /// </summary>
        internal static string Enum_EnumTableType_Nine {
            get {
                return ResourceManager.GetString("Enum_EnumTableType_Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-max.
        /// </summary>
        internal static string Enum_EnumTableType_Six {
            get {
                return ResourceManager.GetString("Enum_EnumTableType_Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-max.
        /// </summary>
        internal static string Enum_EnumTableType_Ten {
            get {
                return ResourceManager.GetString("Enum_EnumTableType_Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-max.
        /// </summary>
        internal static string Enum_EnumTableType_Three {
            get {
                return ResourceManager.GetString("Enum_EnumTableType_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardschat.
        /// </summary>
        internal static string Enum_HandExport_CardsChat {
            get {
                return ResourceManager.GetString("Enum_HandExport_CardsChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICMizer Format.
        /// </summary>
        internal static string Enum_HandExport_ICMizer {
            get {
                return ResourceManager.GetString("Enum_HandExport_ICMizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        internal static string Enum_HandExport_PlainTextHandHistory {
            get {
                return ResourceManager.GetString("Enum_HandExport_PlainTextHandHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokerstrategy.
        /// </summary>
        internal static string Enum_HandExport_PokerStrategy {
            get {
                return ResourceManager.GetString("Enum_HandExport_PokerStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Hand History.
        /// </summary>
        internal static string Enum_HandExport_RawHandHistory {
            get {
                return ResourceManager.GetString("Enum_HandExport_RawHandHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2+2.
        /// </summary>
        internal static string Enum_HandExport_TwoPlusTwo {
            get {
                return ResourceManager.GetString("Enum_HandExport_TwoPlusTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Fold.
        /// </summary>
        internal static string Enum_HandTag_BigFold {
            get {
                return ResourceManager.GetString("Enum_HandTag_BigFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluff.
        /// </summary>
        internal static string Enum_HandTag_Bluff {
            get {
                return ResourceManager.GetString("Enum_HandTag_Bluff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Review.
        /// </summary>
        internal static string Enum_HandTag_ForReview {
            get {
                return ResourceManager.GetString("Enum_HandTag_ForReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero Call.
        /// </summary>
        internal static string Enum_HandTag_HeroCall {
            get {
                return ResourceManager.GetString("Enum_HandTag_HeroCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Tag.
        /// </summary>
        internal static string Enum_HandTag_None {
            get {
                return ResourceManager.GetString("Enum_HandTag_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD HORZ.
        /// </summary>
        internal static string Enum_HudViewType_Horizontal {
            get {
                return ResourceManager.GetString("Enum_HudViewType_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain HUD.
        /// </summary>
        internal static string Enum_HudViewType_Plain {
            get {
                return ResourceManager.GetString("Enum_HudViewType_Plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD VERT 1.
        /// </summary>
        internal static string Enum_HudViewType_Vertical_1 {
            get {
                return ResourceManager.GetString("Enum_HudViewType_Vertical_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD VERT 2.
        /// </summary>
        internal static string Enum_HudViewType_Vertical_2 {
            get {
                return ResourceManager.GetString("Enum_HudViewType_Vertical_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Enum_Likelihood_Custom {
            get {
                return ResourceManager.GetString("Enum_Likelihood_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitely - 100%.
        /// </summary>
        internal static string Enum_Likelihood_Definitely {
            get {
                return ResourceManager.GetString("Enum_Likelihood_Definitely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likely - 75%.
        /// </summary>
        internal static string Enum_Likelihood_Likely {
            get {
                return ResourceManager.GetString("Enum_Likelihood_Likely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Very Likely - 40%.
        /// </summary>
        internal static string Enum_Likelihood_NotVeryLikely {
            get {
                return ResourceManager.GetString("Enum_Likelihood_NotVeryLikely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarely - 10%.
        /// </summary>
        internal static string Enum_Likelihood_Rarely {
            get {
                return ResourceManager.GetString("Enum_Likelihood_Rarely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTN.
        /// </summary>
        internal static string Enum_PredefinedRange_BTN {
            get {
                return ResourceManager.GetString("Enum_PredefinedRange_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO.
        /// </summary>
        internal static string Enum_PredefinedRange_CO {
            get {
                return ResourceManager.GetString("Enum_PredefinedRange_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP.
        /// </summary>
        internal static string Enum_PredefinedRange_MP {
            get {
                return ResourceManager.GetString("Enum_PredefinedRange_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SB.
        /// </summary>
        internal static string Enum_PredefinedRange_SB {
            get {
                return ResourceManager.GetString("Enum_PredefinedRange_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTG.
        /// </summary>
        internal static string Enum_PredefinedRange_UTG {
            get {
                return ResourceManager.GetString("Enum_PredefinedRange_UTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP VPIP%.
        /// </summary>
        internal static string Enum_Stat__VPIP_MP {
            get {
                return ResourceManager.GetString("Enum_Stat__VPIP_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF (Aggression Factor).
        /// </summary>
        internal static string Enum_Stat_AF {
            get {
                return ResourceManager.GetString("Enum_Stat_AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGG%.
        /// </summary>
        internal static string Enum_Stat_AGG {
            get {
                return ResourceManager.GetString("Enum_Stat_AGG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBs.
        /// </summary>
        internal static string Enum_Stat_BBs {
            get {
                return ResourceManager.GetString("Enum_Stat_BBs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bets flop when X to in 3-bet pot IP.
        /// </summary>
        internal static string Enum_Stat_BetFlopCalled3BetPreflopIp {
            get {
                return ResourceManager.GetString("Enum_Stat_BetFlopCalled3BetPreflopIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet/fold flop when PFR raiser.
        /// </summary>
        internal static string Enum_Stat_BetFoldFlopPfrRaiser {
            get {
                return ResourceManager.GetString("Enum_Stat_BetFoldFlopPfrRaiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet When Checked To.
        /// </summary>
        internal static string Enum_Stat_BetWhenCheckedTo {
            get {
                return ResourceManager.GetString("Enum_Stat_BetWhenCheckedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTN Defend to CO Raise.
        /// </summary>
        internal static string Enum_Stat_BTNDefendCORaise {
            get {
                return ResourceManager.GetString("Enum_Stat_BTNDefendCORaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet%.
        /// </summary>
        internal static string Enum_Stat_CBet {
            get {
                return ResourceManager.GetString("Enum_Stat_CBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet 4-Bet Pot%.
        /// </summary>
        internal static string Enum_Stat_CBetInFourBetPot {
            get {
                return ResourceManager.GetString("Enum_Stat_CBetInFourBetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet in 3-Bet Pot%.
        /// </summary>
        internal static string Enum_Stat_CBetInThreeBetPot {
            get {
                return ResourceManager.GetString("Enum_Stat_CBetInThreeBetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet IP%.
        /// </summary>
        internal static string Enum_Stat_CBetIP {
            get {
                return ResourceManager.GetString("Enum_Stat_CBetIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet OOP%.
        /// </summary>
        internal static string Enum_Stat_CBetOOP {
            get {
                return ResourceManager.GetString("Enum_Stat_CBetOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check/fold flop when 3-betting OOP.
        /// </summary>
        internal static string Enum_Stat_CheckFoldFlop3BetOop {
            get {
                return ResourceManager.GetString("Enum_Stat_CheckFoldFlop3BetOop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check/fold flop when PFR OOP.
        /// </summary>
        internal static string Enum_Stat_CheckFoldFlopPfrOop {
            get {
                return ResourceManager.GetString("Enum_Stat_CheckFoldFlopPfrOop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Raise%.
        /// </summary>
        internal static string Enum_Stat_CheckRaise {
            get {
                return ResourceManager.GetString("Enum_Stat_CheckRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check River on BX Line.
        /// </summary>
        internal static string Enum_Stat_CheckRiverOnBXLine {
            get {
                return ResourceManager.GetString("Enum_Stat_CheckRiverOnBXLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call%.
        /// </summary>
        internal static string Enum_Stat_ColdCall {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call BB %.
        /// </summary>
        internal static string Enum_Stat_ColdCall_BB {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCall_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call BTN%.
        /// </summary>
        internal static string Enum_Stat_ColdCall_BN {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCall_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call CO%.
        /// </summary>
        internal static string Enum_Stat_ColdCall_CO {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCall_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call EP%.
        /// </summary>
        internal static string Enum_Stat_ColdCall_EP {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCall_EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call MP%.
        /// </summary>
        internal static string Enum_Stat_ColdCall_MP {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCall_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call SB%.
        /// </summary>
        internal static string Enum_Stat_ColdCall_SB {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCall_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call BB%.
        /// </summary>
        internal static string Enum_Stat_ColdCallBB {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCallBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call BTN%.
        /// </summary>
        internal static string Enum_Stat_ColdCallBTN {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCallBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call CO%.
        /// </summary>
        internal static string Enum_Stat_ColdCallCO {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCallCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call EP%.
        /// </summary>
        internal static string Enum_Stat_ColdCallEP {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCallEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call 4-Bet%.
        /// </summary>
        internal static string Enum_Stat_ColdCallFourBet {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCallFourBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call MP%.
        /// </summary>
        internal static string Enum_Stat_ColdCallMP {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCallMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call SB%.
        /// </summary>
        internal static string Enum_Stat_ColdCallSB {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCallSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call 3-Bet%.
        /// </summary>
        internal static string Enum_Stat_ColdCallThreeBet {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCallThreeBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call vs BTN open%.
        /// </summary>
        internal static string Enum_Stat_ColdCallVsOpenRaiseBTN {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCallVsOpenRaiseBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call vs CO open%.
        /// </summary>
        internal static string Enum_Stat_ColdCallVsOpenRaiseCO {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCallVsOpenRaiseCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call vs SB open%.
        /// </summary>
        internal static string Enum_Stat_ColdCallVsOpenRaiseSB {
            get {
                return ResourceManager.GetString("Enum_Stat_ColdCallVsOpenRaiseSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed Turn C-bet%.
        /// </summary>
        internal static string Enum_Stat_DelayedTurnCBet {
            get {
                return ResourceManager.GetString("Enum_Stat_DelayedTurnCBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donk Bet%.
        /// </summary>
        internal static string Enum_Stat_DonkBet {
            get {
                return ResourceManager.GetString("Enum_Stat_DonkBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Barrel%.
        /// </summary>
        internal static string Enum_Stat_DoubleBarrel {
            get {
                return ResourceManager.GetString("Enum_Stat_DoubleBarrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float Flop%.
        /// </summary>
        internal static string Enum_Stat_FloatFlop {
            get {
                return ResourceManager.GetString("Enum_Stat_FloatFlop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop AGG%.
        /// </summary>
        internal static string Enum_Stat_FlopAGG {
            get {
                return ResourceManager.GetString("Enum_Stat_FlopAGG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet Monotone Pot%.
        /// </summary>
        internal static string Enum_Stat_FlopCBetMonotone {
            get {
                return ResourceManager.GetString("Enum_Stat_FlopCBetMonotone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet MW Pot%.
        /// </summary>
        internal static string Enum_Stat_FlopCBetMW {
            get {
                return ResourceManager.GetString("Enum_Stat_FlopCBetMW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet Rag Flop%.
        /// </summary>
        internal static string Enum_Stat_FlopCBetRag {
            get {
                return ResourceManager.GetString("Enum_Stat_FlopCBetRag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet vs 1 Opp%.
        /// </summary>
        internal static string Enum_Stat_FlopCBetVsOneOpp {
            get {
                return ResourceManager.GetString("Enum_Stat_FlopCBetVsOneOpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet vs 2 Opp%.
        /// </summary>
        internal static string Enum_Stat_FlopCBetVsTwoOpp {
            get {
                return ResourceManager.GetString("Enum_Stat_FlopCBetVsTwoOpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop Check-Raise%.
        /// </summary>
        internal static string Enum_Stat_FlopCheckRaise {
            get {
                return ResourceManager.GetString("Enum_Stat_FlopCheckRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet%.
        /// </summary>
        internal static string Enum_Stat_FoldTo3Bet {
            get {
                return ResourceManager.GetString("Enum_Stat_FoldTo3Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 4-bet%.
        /// </summary>
        internal static string Enum_Stat_FoldTo4Bet {
            get {
                return ResourceManager.GetString("Enum_Stat_FoldTo4Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to C-Bet%.
        /// </summary>
        internal static string Enum_Stat_FoldToCBet {
            get {
                return ResourceManager.GetString("Enum_Stat_FoldToCBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to C-Bet 4-Bet Pot%.
        /// </summary>
        internal static string Enum_Stat_FoldToCBetFromFourBetPot {
            get {
                return ResourceManager.GetString("Enum_Stat_FoldToCBetFromFourBetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to C-Bet 3-Bet Pot%.
        /// </summary>
        internal static string Enum_Stat_FoldToCBetFromThreeBetPot {
            get {
                return ResourceManager.GetString("Enum_Stat_FoldToCBetFromThreeBetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold To Flop Raise.
        /// </summary>
        internal static string Enum_Stat_FoldToFlopRaise {
            get {
                return ResourceManager.GetString("Enum_Stat_FoldToFlopRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold To River  CBet.
        /// </summary>
        internal static string Enum_Stat_FoldToRiverCBet {
            get {
                return ResourceManager.GetString("Enum_Stat_FoldToRiverCBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold To Squeeze.
        /// </summary>
        internal static string Enum_Stat_FoldToSqueez {
            get {
                return ResourceManager.GetString("Enum_Stat_FoldToSqueez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to Steal%.
        /// </summary>
        internal static string Enum_Stat_FoldToSteal {
            get {
                return ResourceManager.GetString("Enum_Stat_FoldToSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold To Turn Raise.
        /// </summary>
        internal static string Enum_Stat_FoldToTurnRaise {
            get {
                return ResourceManager.GetString("Enum_Stat_FoldToTurnRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp%.
        /// </summary>
        internal static string Enum_Stat_Limp {
            get {
                return ResourceManager.GetString("Enum_Stat_Limp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp BTN%.
        /// </summary>
        internal static string Enum_Stat_LimpBtn {
            get {
                return ResourceManager.GetString("Enum_Stat_LimpBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp Call%.
        /// </summary>
        internal static string Enum_Stat_LimpCall {
            get {
                return ResourceManager.GetString("Enum_Stat_LimpCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp CO%.
        /// </summary>
        internal static string Enum_Stat_LimpCo {
            get {
                return ResourceManager.GetString("Enum_Stat_LimpCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp EP%.
        /// </summary>
        internal static string Enum_Stat_LimpEp {
            get {
                return ResourceManager.GetString("Enum_Stat_LimpEp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp Fold%.
        /// </summary>
        internal static string Enum_Stat_LimpFold {
            get {
                return ResourceManager.GetString("Enum_Stat_LimpFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp MP%.
        /// </summary>
        internal static string Enum_Stat_LimpMp {
            get {
                return ResourceManager.GetString("Enum_Stat_LimpMp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp Reraise%.
        /// </summary>
        internal static string Enum_Stat_LimpReraise {
            get {
                return ResourceManager.GetString("Enum_Stat_LimpReraise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp SB%.
        /// </summary>
        internal static string Enum_Stat_LimpSb {
            get {
                return ResourceManager.GetString("Enum_Stat_LimpSb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M-Ratio.
        /// </summary>
        internal static string Enum_Stat_MRatio {
            get {
                return ResourceManager.GetString("Enum_Stat_MRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Won.
        /// </summary>
        internal static string Enum_Stat_NetWon {
            get {
                return ResourceManager.GetString("Enum_Stat_NetWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR%.
        /// </summary>
        internal static string Enum_Stat_PFR {
            get {
                return ResourceManager.GetString("Enum_Stat_PFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR in BB.
        /// </summary>
        internal static string Enum_Stat_PFRInBB {
            get {
                return ResourceManager.GetString("Enum_Stat_PFRInBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR in BTN.
        /// </summary>
        internal static string Enum_Stat_PFRInBTN {
            get {
                return ResourceManager.GetString("Enum_Stat_PFRInBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR in CO.
        /// </summary>
        internal static string Enum_Stat_PFRInCO {
            get {
                return ResourceManager.GetString("Enum_Stat_PFRInCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR in EP.
        /// </summary>
        internal static string Enum_Stat_PFRInEP {
            get {
                return ResourceManager.GetString("Enum_Stat_PFRInEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR in MP.
        /// </summary>
        internal static string Enum_Stat_PFRInMP {
            get {
                return ResourceManager.GetString("Enum_Stat_PFRInMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR in SB.
        /// </summary>
        internal static string Enum_Stat_PFRInSB {
            get {
                return ResourceManager.GetString("Enum_Stat_PFRInSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Profile Icon.
        /// </summary>
        internal static string Enum_Stat_PlayerInfoIcon {
            get {
                return ResourceManager.GetString("Enum_Stat_PlayerInfoIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise C-Bet%.
        /// </summary>
        internal static string Enum_Stat_RaiseCBet {
            get {
                return ResourceManager.GetString("Enum_Stat_RaiseCBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Flop%.
        /// </summary>
        internal static string Enum_Stat_RaiseFlop {
            get {
                return ResourceManager.GetString("Enum_Stat_RaiseFlop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Frequency Factor.
        /// </summary>
        internal static string Enum_Stat_RaiseFrequencyFactor {
            get {
                return ResourceManager.GetString("Enum_Stat_RaiseFrequencyFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise River%.
        /// </summary>
        internal static string Enum_Stat_RaiseRiver {
            get {
                return ResourceManager.GetString("Enum_Stat_RaiseRiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Turn%.
        /// </summary>
        internal static string Enum_Stat_RaiseTurn {
            get {
                return ResourceManager.GetString("Enum_Stat_RaiseTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent AGG%.
        /// </summary>
        internal static string Enum_Stat_RecentAgg {
            get {
                return ResourceManager.GetString("Enum_Stat_RecentAgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River AGG%.
        /// </summary>
        internal static string Enum_Stat_RiverAGG {
            get {
                return ResourceManager.GetString("Enum_Stat_RiverAGG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Check-Raise%.
        /// </summary>
        internal static string Enum_Stat_RiverCheckRaise {
            get {
                return ResourceManager.GetString("Enum_Stat_RiverCheckRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen River%.
        /// </summary>
        internal static string Enum_Stat_RiverSeen {
            get {
                return ResourceManager.GetString("Enum_Stat_RiverSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-bet%.
        /// </summary>
        internal static string Enum_Stat_S3Bet {
            get {
                return ResourceManager.GetString("Enum_Stat_S3Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BB%.
        /// </summary>
        internal static string Enum_Stat_S3BetBB {
            get {
                return ResourceManager.GetString("Enum_Stat_S3BetBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BTN%.
        /// </summary>
        internal static string Enum_Stat_S3BetBTN {
            get {
                return ResourceManager.GetString("Enum_Stat_S3BetBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet CO%.
        /// </summary>
        internal static string Enum_Stat_S3BetCO {
            get {
                return ResourceManager.GetString("Enum_Stat_S3BetCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet IP%.
        /// </summary>
        internal static string Enum_Stat_S3BetIP {
            get {
                return ResourceManager.GetString("Enum_Stat_S3BetIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet MP%.
        /// </summary>
        internal static string Enum_Stat_S3BetMP {
            get {
                return ResourceManager.GetString("Enum_Stat_S3BetMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet OOP%.
        /// </summary>
        internal static string Enum_Stat_S3BetOOP {
            get {
                return ResourceManager.GetString("Enum_Stat_S3BetOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet SB%.
        /// </summary>
        internal static string Enum_Stat_S3BetSB {
            get {
                return ResourceManager.GetString("Enum_Stat_S3BetSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-bet%.
        /// </summary>
        internal static string Enum_Stat_S4Bet {
            get {
                return ResourceManager.GetString("Enum_Stat_S4Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet BB%.
        /// </summary>
        internal static string Enum_Stat_S4BetBB {
            get {
                return ResourceManager.GetString("Enum_Stat_S4BetBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet BTN%.
        /// </summary>
        internal static string Enum_Stat_S4BetBTN {
            get {
                return ResourceManager.GetString("Enum_Stat_S4BetBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet CO%.
        /// </summary>
        internal static string Enum_Stat_S4BetCO {
            get {
                return ResourceManager.GetString("Enum_Stat_S4BetCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet EP%.
        /// </summary>
        internal static string Enum_Stat_S4BetEP {
            get {
                return ResourceManager.GetString("Enum_Stat_S4BetEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet MP%.
        /// </summary>
        internal static string Enum_Stat_S4BetMP {
            get {
                return ResourceManager.GetString("Enum_Stat_S4BetMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet SB%.
        /// </summary>
        internal static string Enum_Stat_S4BetSB {
            get {
                return ResourceManager.GetString("Enum_Stat_S4BetSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squeeze%.
        /// </summary>
        internal static string Enum_Stat_Squeeze {
            get {
                return ResourceManager.GetString("Enum_Stat_Squeeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steal%.
        /// </summary>
        internal static string Enum_Stat_Steal {
            get {
                return ResourceManager.GetString("Enum_Stat_Steal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BB%.
        /// </summary>
        internal static string Enum_Stat_ThreeBet_BB {
            get {
                return ResourceManager.GetString("Enum_Stat_ThreeBet_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BTN%.
        /// </summary>
        internal static string Enum_Stat_ThreeBet_BN {
            get {
                return ResourceManager.GetString("Enum_Stat_ThreeBet_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet CO%.
        /// </summary>
        internal static string Enum_Stat_ThreeBet_CO {
            get {
                return ResourceManager.GetString("Enum_Stat_ThreeBet_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet EP%.
        /// </summary>
        internal static string Enum_Stat_ThreeBet_EP {
            get {
                return ResourceManager.GetString("Enum_Stat_ThreeBet_EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet MP%.
        /// </summary>
        internal static string Enum_Stat_ThreeBet_MP {
            get {
                return ResourceManager.GetString("Enum_Stat_ThreeBet_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet SB%.
        /// </summary>
        internal static string Enum_Stat_ThreeBet_SB {
            get {
                return ResourceManager.GetString("Enum_Stat_ThreeBet_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet vs. Steal.
        /// </summary>
        internal static string Enum_Stat_ThreeBetVsSteal {
            get {
                return ResourceManager.GetString("Enum_Stat_ThreeBetVsSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hands.
        /// </summary>
        internal static string Enum_Stat_TotalHands {
            get {
                return ResourceManager.GetString("Enum_Stat_TotalHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Aggression % (TAP).
        /// </summary>
        internal static string Enum_Stat_TrueAggression {
            get {
                return ResourceManager.GetString("Enum_Stat_TrueAggression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn AGG%.
        /// </summary>
        internal static string Enum_Stat_TurnAGG {
            get {
                return ResourceManager.GetString("Enum_Stat_TurnAGG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Check-Raise%.
        /// </summary>
        internal static string Enum_Stat_TurnCheckRaise {
            get {
                return ResourceManager.GetString("Enum_Stat_TurnCheckRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen Turn%.
        /// </summary>
        internal static string Enum_Stat_TurnSeen {
            get {
                return ResourceManager.GetString("Enum_Stat_TurnSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO-PFR BB.
        /// </summary>
        internal static string Enum_Stat_UO_PFR_BB {
            get {
                return ResourceManager.GetString("Enum_Stat_UO_PFR_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO-PFR BTN.
        /// </summary>
        internal static string Enum_Stat_UO_PFR_BN {
            get {
                return ResourceManager.GetString("Enum_Stat_UO_PFR_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO-PFR CO.
        /// </summary>
        internal static string Enum_Stat_UO_PFR_CO {
            get {
                return ResourceManager.GetString("Enum_Stat_UO_PFR_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO-PFR EP.
        /// </summary>
        internal static string Enum_Stat_UO_PFR_EP {
            get {
                return ResourceManager.GetString("Enum_Stat_UO_PFR_EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO-PFR MP.
        /// </summary>
        internal static string Enum_Stat_UO_PFR_MP {
            get {
                return ResourceManager.GetString("Enum_Stat_UO_PFR_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO-PFR SB.
        /// </summary>
        internal static string Enum_Stat_UO_PFR_SB {
            get {
                return ResourceManager.GetString("Enum_Stat_UO_PFR_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP%.
        /// </summary>
        internal static string Enum_Stat_VPIP {
            get {
                return ResourceManager.GetString("Enum_Stat_VPIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP BB%.
        /// </summary>
        internal static string Enum_Stat_VPIP_BB {
            get {
                return ResourceManager.GetString("Enum_Stat_VPIP_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP BTN%.
        /// </summary>
        internal static string Enum_Stat_VPIP_BN {
            get {
                return ResourceManager.GetString("Enum_Stat_VPIP_BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP CO%.
        /// </summary>
        internal static string Enum_Stat_VPIP_CO {
            get {
                return ResourceManager.GetString("Enum_Stat_VPIP_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP EP%.
        /// </summary>
        internal static string Enum_Stat_VPIP_EP {
            get {
                return ResourceManager.GetString("Enum_Stat_VPIP_EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP MP%.
        /// </summary>
        internal static string Enum_Stat_VPIP_MP {
            get {
                return ResourceManager.GetString("Enum_Stat_VPIP_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP SB%.
        /// </summary>
        internal static string Enum_Stat_VPIP_SB {
            get {
                return ResourceManager.GetString("Enum_Stat_VPIP_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W$SD.
        /// </summary>
        internal static string Enum_Stat_WSSD {
            get {
                return ResourceManager.GetString("Enum_Stat_WSSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTSD.
        /// </summary>
        internal static string Enum_Stat_WTSD {
            get {
                return ResourceManager.GetString("Enum_Stat_WTSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWSF.
        /// </summary>
        internal static string Enum_Stat_WWSF {
            get {
                return ResourceManager.GetString("Enum_Stat_WWSF", resourceCulture);
            }
        }
    }
}
