//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveHUD.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveHUD.Common.Resources.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Main_ContextMenu_All {
            get {
                return ResourceManager.GetString("Main_ContextMenu_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All HUDs Same As.
        /// </summary>
        internal static string Main_ContextMenu_ApplyPositions {
            get {
                return ResourceManager.GetString("Main_ContextMenu_ApplyPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat #{0}.
        /// </summary>
        internal static string Main_ContextMenu_ApplyPositionsAsSeat {
            get {
                return ResourceManager.GetString("Main_ContextMenu_ApplyPositionsAsSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Equity.
        /// </summary>
        internal static string Main_ContextMenu_CalculateEquity {
            get {
                return ResourceManager.GetString("Main_ContextMenu_CalculateEquity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Hand.
        /// </summary>
        internal static string Main_ContextMenu_DeleteHand {
            get {
                return ResourceManager.GetString("Main_ContextMenu_DeleteHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tournament.
        /// </summary>
        internal static string Main_ContextMenu_DeleteTournament {
            get {
                return ResourceManager.GetString("Main_ContextMenu_DeleteTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Note.
        /// </summary>
        internal static string Main_ContextMenu_EditNote {
            get {
                return ResourceManager.GetString("Main_ContextMenu_EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tournament.
        /// </summary>
        internal static string Main_ContextMenu_EditTournament {
            get {
                return ResourceManager.GetString("Main_ContextMenu_EditTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd party apps.
        /// </summary>
        internal static string Main_ContextMenu_ExportGridHands {
            get {
                return ResourceManager.GetString("Main_ContextMenu_ExportGridHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Hand.
        /// </summary>
        internal static string Main_ContextMenu_ExportHand {
            get {
                return ResourceManager.GetString("Main_ContextMenu_ExportHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Hands for 3rd party apps.
        /// </summary>
        internal static string Main_ContextMenu_ExportHands {
            get {
                return ResourceManager.GetString("Main_ContextMenu_ExportHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Last Hand.
        /// </summary>
        internal static string Main_ContextMenu_ExportLastHand {
            get {
                return ResourceManager.GetString("Main_ContextMenu_ExportLastHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Report.
        /// </summary>
        internal static string Main_ContextMenu_ExportToExcel {
            get {
                return ResourceManager.GetString("Main_ContextMenu_ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load HUD.
        /// </summary>
        internal static string Main_ContextMenu_LoadHud {
            get {
                return ResourceManager.GetString("Main_ContextMenu_LoadHud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Note.
        /// </summary>
        internal static string Main_ContextMenu_MakeNote {
            get {
                return ResourceManager.GetString("Main_ContextMenu_MakeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Report.
        /// </summary>
        internal static string Main_ContextMenu_RefreshReport {
            get {
                return ResourceManager.GetString("Main_ContextMenu_RefreshReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay Hand.
        /// </summary>
        internal static string Main_ContextMenu_ReplayHand {
            get {
                return ResourceManager.GetString("Main_ContextMenu_ReplayHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay Last Hand.
        /// </summary>
        internal static string Main_ContextMenu_ReplayLastHand {
            get {
                return ResourceManager.GetString("Main_ContextMenu_ReplayLastHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save HUD Position.
        /// </summary>
        internal static string Main_ContextMenu_SaveHudPosition {
            get {
                return ResourceManager.GetString("Main_ContextMenu_SaveHudPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Hand.
        /// </summary>
        internal static string Main_ContextMenu_TagHand {
            get {
                return ResourceManager.GetString("Main_ContextMenu_TagHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Last Hand.
        /// </summary>
        internal static string Main_ContextMenu_TagLastHand {
            get {
                return ResourceManager.GetString("Main_ContextMenu_TagLastHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Last 3 Hands.
        /// </summary>
        internal static string Main_ContextMenu_TagLastHands {
            get {
                return ResourceManager.GetString("Main_ContextMenu_TagLastHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat HUD as.
        /// </summary>
        internal static string Main_ContextMenu_TreatAs {
            get {
                return ResourceManager.GetString("Main_ContextMenu_TreatAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat as {0}-max.
        /// </summary>
        internal static string Main_ContextMenu_TreatAsTableSize {
            get {
                return ResourceManager.GetString("Main_ContextMenu_TreatAsTableSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Main_RadWindow_Close {
            get {
                return ResourceManager.GetString("Main_RadWindow_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        internal static string Main_RadWindow_Maximize {
            get {
                return ResourceManager.GetString("Main_RadWindow_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string Main_RadWindow_Minimize {
            get {
                return ResourceManager.GetString("Main_RadWindow_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Main_RadWindow_Restore {
            get {
                return ResourceManager.GetString("Main_RadWindow_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD Replayer: {0} - {1}.
        /// </summary>
        internal static string Main_ReplayerHeader {
            get {
                return ResourceManager.GetString("Main_ReplayerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 100.
        /// </summary>
        internal static string Main_ReportGadgetView_Last100 {
            get {
                return ResourceManager.GetString("Main_ReportGadgetView_Last100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 1000.
        /// </summary>
        internal static string Main_ReportGadgetView_Last1000 {
            get {
                return ResourceManager.GetString("Main_ReportGadgetView_Last1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 250.
        /// </summary>
        internal static string Main_ReportGadgetView_Last250 {
            get {
                return ResourceManager.GetString("Main_ReportGadgetView_Last250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Main_ReportGadgetView_LastAll {
            get {
                return ResourceManager.GetString("Main_ReportGadgetView_LastAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD found a potential settings problem for the following poker client(s): {0}
        ///
        ///Please make sure to:
        ///{1}
        ///
        ///For more infromation on  how to enable these settings, please see the following link:.
        /// </summary>
        internal static string Main_SiteSettingsMismatch_PokerStars {
            get {
                return ResourceManager.GetString("Main_SiteSettingsMismatch_PokerStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        internal static string Main_TopMenu_Apps {
            get {
                return ResourceManager.GetString("Main_TopMenu_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Main_TopMenu_Dashboard {
            get {
                return ResourceManager.GetString("Main_TopMenu_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD.
        /// </summary>
        internal static string Main_TopMenu_Hud {
            get {
                return ResourceManager.GetString("Main_TopMenu_Hud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        internal static string Main_TopMenu_Tournament {
            get {
                return ResourceManager.GetString("Main_TopMenu_Tournament", resourceCulture);
            }
        }
    }
}
