//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveHUD.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveHUD.Common.Resources.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Notifications_DeleteHand_Cancel {
            get {
                return ResourceManager.GetString("Notifications_DeleteHand_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these hands?.
        /// </summary>
        internal static string Notifications_DeleteHand_MultipleContent {
            get {
                return ResourceManager.GetString("Notifications_DeleteHand_MultipleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} hands.
        /// </summary>
        internal static string Notifications_DeleteHand_MultipleTitle {
            get {
                return ResourceManager.GetString("Notifications_DeleteHand_MultipleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this hand?.
        /// </summary>
        internal static string Notifications_DeleteHand_SingleContent {
            get {
                return ResourceManager.GetString("Notifications_DeleteHand_SingleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete hand.
        /// </summary>
        internal static string Notifications_DeleteHand_SingleTitle {
            get {
                return ResourceManager.GetString("Notifications_DeleteHand_SingleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Notifications_DeleteHand_Yes {
            get {
                return ResourceManager.GetString("Notifications_DeleteHand_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected tournament?.
        /// </summary>
        internal static string Notifications_DeleteTournament_Content {
            get {
                return ResourceManager.GetString("Notifications_DeleteTournament_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tournament.
        /// </summary>
        internal static string Notifications_DeleteTournament_Title {
            get {
                return ResourceManager.GetString("Notifications_DeleteTournament_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Notifications_HudLayout_DeleteHudCancel {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_DeleteHudCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this HUD?.
        /// </summary>
        internal static string Notifications_HudLayout_DeleteHudContent {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_DeleteHudContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete HUD.
        /// </summary>
        internal static string Notifications_HudLayout_DeleteHudTitle {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_DeleteHudTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Notifications_HudLayout_DeleteHudYes {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_DeleteHudYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One full hand must be played before HUD appears. Please wait..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_Adda52 {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_Adda52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD cannot load a HUD since Crazy Pineapple mode isn&apos;t supported..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_Adda52CrazyPineappleNotSupported {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_Adda52CrazyPineappleNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD cannot load a HUD since Adda52 was launched prior to DriveHUD being loaded. DriveHUD needs to be loaded first, then Adda52 can be launched..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_Adda52FailedToLoad {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_Adda52FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One full hand must be played before HUD appears. Please wait..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_Ignition {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_Ignition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD cannot load a HUD since the table was open prior to DriveHUD being loaded. DriveHUD needs to be loaded first, then a table for Ignition can be loaded..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_IgnitionNotDetectable {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_IgnitionNotDetectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD can&apos;t be loaded. DH License doesn&apos;t support this table..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_NoLicense {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_NoLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hud isn&apos;t supported in fast fold mode, but hands will be imported..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_NotSupportedFastFold {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_NotSupportedFastFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One full hand must be played before HUD appears. Please wait..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_PK {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD cannot load a HUD since the table was open prior to DriveHUD being loaded. DriveHUD needs to be loaded first, then a table for PokerKing can be loaded..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_PK_CanNotBeCapturedText {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_PK_CanNotBeCapturedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD can&apos;t be loaded. PRO version of catcher is required..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_PK_NoLicense {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_PK_NoLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One full hand must be played before HUD appears. Please wait..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_PM {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM catcher only supports one account per table..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_PM_AccountPerTable {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_PM_AccountPerTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD can&apos;t be loaded. PRO version of catcher is required..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_PM_NoLicense {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_PM_NoLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD can&apos;t be loaded. Relogin is required..
        /// </summary>
        internal static string Notifications_HudLayout_PreLoadingText_PM_Relogin {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_PreLoadingText_PM_Relogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default layout can&apos;t be overwritten..
        /// </summary>
        internal static string Notifications_HudLayout_SaveAsFailedDefaultLayout {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_SaveAsFailedDefaultLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed!.
        /// </summary>
        internal static string Notifications_HudLayout_SaveAsFailedTitle {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_SaveAsFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes have been made to your HUD layout. Would you like to save them now?.
        /// </summary>
        internal static string Notifications_HudLayout_SaveDesignContent {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_SaveDesignContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Notifications_HudLayout_SaveDesignNo {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_SaveDesignNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        internal static string Notifications_HudLayout_SaveDesignTitle {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_SaveDesignTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Notifications_HudLayout_SaveDesignYes {
            get {
                return ResourceManager.GetString("Notifications_HudLayout_SaveDesignYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rebuild stats. Please contact support..
        /// </summary>
        internal static string Notifications_RebuildStats_FailedMessage {
            get {
                return ResourceManager.GetString("Notifications_RebuildStats_FailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed!.
        /// </summary>
        internal static string Notifications_RebuildStats_FailedTitle {
            get {
                return ResourceManager.GetString("Notifications_RebuildStats_FailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats have been rebuilt successfully..
        /// </summary>
        internal static string Notifications_RebuildStats_SucceedMessage {
            get {
                return ResourceManager.GetString("Notifications_RebuildStats_SucceedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeed!.
        /// </summary>
        internal static string Notifications_RebuildStats_SucceedTitle {
            get {
                return ResourceManager.GetString("Notifications_RebuildStats_SucceedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set Player ID in order to see data..
        /// </summary>
        internal static string Notifications_SelectPlayer_Message {
            get {
                return ResourceManager.GetString("Notifications_SelectPlayer_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD.
        /// </summary>
        internal static string Notifications_SelectPlayer_Title {
            get {
                return ResourceManager.GetString("Notifications_SelectPlayer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Notifications_Update_Cancel {
            get {
                return ResourceManager.GetString("Notifications_Update_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD v.{0} is available.
        /// </summary>
        internal static string Notifications_Update_Header {
            get {
                return ResourceManager.GetString("Notifications_Update_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD is being stopped....
        /// </summary>
        internal static string Notifications_Update_StoppingHUD {
            get {
                return ResourceManager.GetString("Notifications_Update_StoppingHUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD Update Notice.
        /// </summary>
        internal static string Notifications_Update_Title {
            get {
                return ResourceManager.GetString("Notifications_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Notifications_Update_Update {
            get {
                return ResourceManager.GetString("Notifications_Update_Update", resourceCulture);
            }
        }
    }
}
