//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveHUD.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgressMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgressMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveHUD.Common.Resources.ProgressMessages", typeof(ProgressMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing.
        /// </summary>
        internal static string Progress_Parsing {
            get {
                return ResourceManager.GetString("Progress_Parsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading {0}.
        /// </summary>
        internal static string Progress_ReadingFile {
            get {
                return ResourceManager.GetString("Progress_ReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilding statistics.
        /// </summary>
        internal static string Progress_RebuildingStatistics {
            get {
                return ResourceManager.GetString("Progress_RebuildingStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilding statistics {0}/{1}.
        /// </summary>
        internal static string Progress_RebuildingStatistics_Status {
            get {
                return ResourceManager.GetString("Progress_RebuildingStatistics_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovering statistics.
        /// </summary>
        internal static string Progress_RecoveringStatistics {
            get {
                return ResourceManager.GetString("Progress_RecoveringStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning folder.
        /// </summary>
        internal static string Progress_ScanningFolder {
            get {
                return ResourceManager.GetString("Progress_ScanningFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting import.
        /// </summary>
        internal static string Progress_StartingImport {
            get {
                return ResourceManager.GetString("Progress_StartingImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop import.
        /// </summary>
        internal static string Progress_Stop {
            get {
                return ResourceManager.GetString("Progress_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping import.
        /// </summary>
        internal static string Progress_StoppingImport {
            get {
                return ResourceManager.GetString("Progress_StoppingImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress {0} of {1}.
        /// </summary>
        internal static string Progress_Temp {
            get {
                return ResourceManager.GetString("Progress_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating statistic {0}/{1} Duplicate hands: {2}.
        /// </summary>
        internal static string Progress_UpdatingData {
            get {
                return ResourceManager.GetString("Progress_UpdatingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuuming database.
        /// </summary>
        internal static string Progress_VacuumingDatabase {
            get {
                return ResourceManager.GetString("Progress_VacuumingDatabase", resourceCulture);
            }
        }
    }
}
