//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveHUD.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveHUD.Common.Resources.Reports", typeof(Reports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All players.
        /// </summary>
        internal static string Reports_AllPlayers_PlayerType {
            get {
                return ResourceManager.GetString("Reports_AllPlayers_PlayerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet%.
        /// </summary>
        internal static string Reports_Column_3Bet {
            get {
                return ResourceManager.GetString("Reports_Column_3Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BB%.
        /// </summary>
        internal static string Reports_Column_3Bet_BB {
            get {
                return ResourceManager.GetString("Reports_Column_3Bet_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BTN%.
        /// </summary>
        internal static string Reports_Column_3Bet_BTN {
            get {
                return ResourceManager.GetString("Reports_Column_3Bet_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet CO%.
        /// </summary>
        internal static string Reports_Column_3Bet_CO {
            get {
                return ResourceManager.GetString("Reports_Column_3Bet_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet IP%.
        /// </summary>
        internal static string Reports_Column_3Bet_IP {
            get {
                return ResourceManager.GetString("Reports_Column_3Bet_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet MP%.
        /// </summary>
        internal static string Reports_Column_3Bet_MP {
            get {
                return ResourceManager.GetString("Reports_Column_3Bet_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet OOP%.
        /// </summary>
        internal static string Reports_Column_3Bet_OOP {
            get {
                return ResourceManager.GetString("Reports_Column_3Bet_OOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet SB%.
        /// </summary>
        internal static string Reports_Column_3Bet_SB {
            get {
                return ResourceManager.GetString("Reports_Column_3Bet_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet Call%.
        /// </summary>
        internal static string Reports_Column_3BetCall {
            get {
                return ResourceManager.GetString("Reports_Column_3BetCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet vs. Steal%.
        /// </summary>
        internal static string Reports_Column_3BetVsSteal {
            get {
                return ResourceManager.GetString("Reports_Column_3BetVsSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet%.
        /// </summary>
        internal static string Reports_Column_4Bet {
            get {
                return ResourceManager.GetString("Reports_Column_4Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet BB%.
        /// </summary>
        internal static string Reports_Column_4Bet_BB {
            get {
                return ResourceManager.GetString("Reports_Column_4Bet_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet BTN%.
        /// </summary>
        internal static string Reports_Column_4Bet_BTN {
            get {
                return ResourceManager.GetString("Reports_Column_4Bet_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet CO%.
        /// </summary>
        internal static string Reports_Column_4Bet_CO {
            get {
                return ResourceManager.GetString("Reports_Column_4Bet_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet EP%.
        /// </summary>
        internal static string Reports_Column_4Bet_EP {
            get {
                return ResourceManager.GetString("Reports_Column_4Bet_EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet MP%.
        /// </summary>
        internal static string Reports_Column_4Bet_MP {
            get {
                return ResourceManager.GetString("Reports_Column_4Bet_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet SB%.
        /// </summary>
        internal static string Reports_Column_4Bet_SB {
            get {
                return ResourceManager.GetString("Reports_Column_4Bet_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Bet Range.
        /// </summary>
        internal static string Reports_Column_4BetRange {
            get {
                return ResourceManager.GetString("Reports_Column_4BetRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-Bet%.
        /// </summary>
        internal static string Reports_Column_5Bet {
            get {
                return ResourceManager.GetString("Reports_Column_5Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF.
        /// </summary>
        internal static string Reports_Column_AF {
            get {
                return ResourceManager.GetString("Reports_Column_AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agg.
        /// </summary>
        internal static string Reports_Column_Agg {
            get {
                return ResourceManager.GetString("Reports_Column_Agg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agg%.
        /// </summary>
        internal static string Reports_Column_AggPercent {
            get {
                return ResourceManager.GetString("Reports_Column_AggPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bb/100.
        /// </summary>
        internal static string Reports_Column_BB100 {
            get {
                return ResourceManager.GetString("Reports_Column_BB100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bets flop when X to in 3-bet pot IP%.
        /// </summary>
        internal static string Reports_Column_BetFlopCalled3BetPreflopIp {
            get {
                return ResourceManager.GetString("Reports_Column_BetFlopCalled3BetPreflopIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet when checked to on Flop in 3-Bet Pot%.
        /// </summary>
        internal static string Reports_Column_BetFlopWhenCheckedToIn3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_BetFlopWhenCheckedToIn3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet Flop when Checked to SRP%.
        /// </summary>
        internal static string Reports_Column_BetFlopWhenCheckedToSRP {
            get {
                return ResourceManager.GetString("Reports_Column_BetFlopWhenCheckedToSRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet/fold flop when PFR raiser%.
        /// </summary>
        internal static string Reports_Column_BetFoldFlopPfrRaiser {
            get {
                return ResourceManager.GetString("Reports_Column_BetFoldFlopPfrRaiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet River on BX Line%.
        /// </summary>
        internal static string Reports_Column_BetRiverOnBXLine {
            get {
                return ResourceManager.GetString("Reports_Column_BetRiverOnBXLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet when checked to on River in 3-Bet Pot%.
        /// </summary>
        internal static string Reports_Column_BetRiverWhenCheckedToIn3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_BetRiverWhenCheckedToIn3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet River when Checked to SRP%.
        /// </summary>
        internal static string Reports_Column_BetRiverWhenCheckedToSRP {
            get {
                return ResourceManager.GetString("Reports_Column_BetRiverWhenCheckedToSRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet when checked to on Turn in 3-Bet Pot%.
        /// </summary>
        internal static string Reports_Column_BetTurnWhenCheckedToIn3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_BetTurnWhenCheckedToIn3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet Turn when Checked to SRP%.
        /// </summary>
        internal static string Reports_Column_BetTurnWhenCheckedToSRP {
            get {
                return ResourceManager.GetString("Reports_Column_BetTurnWhenCheckedToSRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet When Checked To%.
        /// </summary>
        internal static string Reports_Column_BetWhenCheckedTo {
            get {
                return ResourceManager.GetString("Reports_Column_BetWhenCheckedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blinds Fold to Steal%.
        /// </summary>
        internal static string Reports_Column_BlindsFoldToSteal {
            get {
                return ResourceManager.GetString("Reports_Column_BlindsFoldToSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blinds Re-raise Steal%.
        /// </summary>
        internal static string Reports_Column_BlindsReRaiseSteal {
            get {
                return ResourceManager.GetString("Reports_Column_BlindsReRaiseSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTN Defend to CO Raise%.
        /// </summary>
        internal static string Reports_Column_BTNDefendCORaise {
            get {
                return ResourceManager.GetString("Reports_Column_BTNDefendCORaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy-in.
        /// </summary>
        internal static string Reports_Column_Buyin {
            get {
                return ResourceManager.GetString("Reports_Column_Buyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Raise &amp; Call vs. Flop C-bet%.
        /// </summary>
        internal static string Reports_Column_CalledCheckRaiseVsFlopCBet {
            get {
                return ResourceManager.GetString("Reports_Column_CalledCheckRaiseVsFlopCBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Turn Check-Raise %.
        /// </summary>
        internal static string Reports_Column_CalledTurnCheckRaise {
            get {
                return ResourceManager.GetString("Reports_Column_CalledTurnCheckRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Flop C-Bet IP%.
        /// </summary>
        internal static string Reports_Column_CallFlopCBetIP {
            get {
                return ResourceManager.GetString("Reports_Column_CallFlopCBetIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Flop C-Bet OOP%.
        /// </summary>
        internal static string Reports_Column_CallFlopCBetOOP {
            get {
                return ResourceManager.GetString("Reports_Column_CallFlopCBetOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call River Raise%.
        /// </summary>
        internal static string Reports_Column_CallRiverRaise {
            get {
                return ResourceManager.GetString("Reports_Column_CallRiverRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet%.
        /// </summary>
        internal static string Reports_Column_CBet {
            get {
                return ResourceManager.GetString("Reports_Column_CBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet IP%.
        /// </summary>
        internal static string Reports_Column_CBet_IP {
            get {
                return ResourceManager.GetString("Reports_Column_CBet_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet Monotone Pot%.
        /// </summary>
        internal static string Reports_Column_CBet_MonotonePot {
            get {
                return ResourceManager.GetString("Reports_Column_CBet_MonotonePot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet MW Pot%.
        /// </summary>
        internal static string Reports_Column_CBet_MWPot {
            get {
                return ResourceManager.GetString("Reports_Column_CBet_MWPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet OOP%.
        /// </summary>
        internal static string Reports_Column_CBet_OOP {
            get {
                return ResourceManager.GetString("Reports_Column_CBet_OOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet Rag Flop%.
        /// </summary>
        internal static string Reports_Column_CBet_RagFlop {
            get {
                return ResourceManager.GetString("Reports_Column_CBet_RagFlop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet 4-Bet Pot%.
        /// </summary>
        internal static string Reports_Column_CBet4BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_CBet4BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet in 3-Bet Pot%.
        /// </summary>
        internal static string Reports_Column_CBetIn3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_CBetIn3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet then Fold Flop SRP%.
        /// </summary>
        internal static string Reports_Column_CBetThenFoldFlopSRP {
            get {
                return ResourceManager.GetString("Reports_Column_CBetThenFoldFlopSRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet vs 1 Opp%.
        /// </summary>
        internal static string Reports_Column_CBetVs1Opp {
            get {
                return ResourceManager.GetString("Reports_Column_CBetVs1Opp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Bet vs 2 Opp%.
        /// </summary>
        internal static string Reports_Column_CBetVs2Opp {
            get {
                return ResourceManager.GetString("Reports_Column_CBetVs2Opp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks Flop as PFR and Calls Turn%.
        /// </summary>
        internal static string Reports_Column_CheckFlopAsPFRAndCallOnTurn {
            get {
                return ResourceManager.GetString("Reports_Column_CheckFlopAsPFRAndCallOnTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks Flop as PFR and Fold to Turn Bet%.
        /// </summary>
        internal static string Reports_Column_CheckFlopAsPFRAndFoldOnTurn {
            get {
                return ResourceManager.GetString("Reports_Column_CheckFlopAsPFRAndFoldOnTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Flop as PFR and Fold to river bet IP 3B Pot%.
        /// </summary>
        internal static string Reports_Column_CheckFlopAsPFRAndFoldToRiverBetIP3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_CheckFlopAsPFRAndFoldToRiverBetIP3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Flop as PFR and Fold to river bet IP SRP%.
        /// </summary>
        internal static string Reports_Column_CheckFlopAsPFRAndFoldToRiverBetIPSRP {
            get {
                return ResourceManager.GetString("Reports_Column_CheckFlopAsPFRAndFoldToRiverBetIPSRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Flop as PFR and Fold to river bet OOP 3B Pot%.
        /// </summary>
        internal static string Reports_Column_CheckFlopAsPFRAndFoldToRiverBetOOP3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_CheckFlopAsPFRAndFoldToRiverBetOOP3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Flop as PFR and Fold to river bet OOP SRP%.
        /// </summary>
        internal static string Reports_Column_CheckFlopAsPFRAndFoldToRiverBetOOPSRP {
            get {
                return ResourceManager.GetString("Reports_Column_CheckFlopAsPFRAndFoldToRiverBetOOPSRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Flop as PFR and Fold to turn bet IP 3B Pot%.
        /// </summary>
        internal static string Reports_Column_CheckFlopAsPFRAndFoldToTurnBetIP3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_CheckFlopAsPFRAndFoldToTurnBetIP3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Flop as PFR and Fold to turn bet IP SRP%.
        /// </summary>
        internal static string Reports_Column_CheckFlopAsPFRAndFoldToTurnBetIPSRP {
            get {
                return ResourceManager.GetString("Reports_Column_CheckFlopAsPFRAndFoldToTurnBetIPSRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Flop as PFR and Fold to turn bet OOP 3B Pot%.
        /// </summary>
        internal static string Reports_Column_CheckFlopAsPFRAndFoldToTurnBetOOP3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_CheckFlopAsPFRAndFoldToTurnBetOOP3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Flop as PFR and Fold to turn bet OOP SRP%.
        /// </summary>
        internal static string Reports_Column_CheckFlopAsPFRAndFoldToTurnBetOOPSRP {
            get {
                return ResourceManager.GetString("Reports_Column_CheckFlopAsPFRAndFoldToTurnBetOOPSRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks Flop as PFR and Raises Turn Bet%.
        /// </summary>
        internal static string Reports_Column_CheckFlopAsPFRAndRaiseOnTurn {
            get {
                return ResourceManager.GetString("Reports_Column_CheckFlopAsPFRAndRaiseOnTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks Flop as PFR and X/C OOP on Turn%.
        /// </summary>
        internal static string Reports_Column_CheckFlopAsPFRAndXCOnTurnOOP {
            get {
                return ResourceManager.GetString("Reports_Column_CheckFlopAsPFRAndXCOnTurnOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks Flop as PFR and X/F OOP on Turn%.
        /// </summary>
        internal static string Reports_Column_CheckFlopAsPFRAndXFOnTurnOOP {
            get {
                return ResourceManager.GetString("Reports_Column_CheckFlopAsPFRAndXFOnTurnOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Raise%.
        /// </summary>
        internal static string Reports_Column_CheckRaise {
            get {
                return ResourceManager.GetString("Reports_Column_CheckRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Raise Flop C-Bet%.
        /// </summary>
        internal static string Reports_Column_CheckRaisedFlopCBet {
            get {
                return ResourceManager.GetString("Reports_Column_CheckRaisedFlopCBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-raise flop as PFR%.
        /// </summary>
        internal static string Reports_Column_CheckRaiseFlopAsPFR {
            get {
                return ResourceManager.GetString("Reports_Column_CheckRaiseFlopAsPFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check River after BB Line%.
        /// </summary>
        internal static string Reports_Column_CheckRiverAfterBBLine {
            get {
                return ResourceManager.GetString("Reports_Column_CheckRiverAfterBBLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check River On BX Line%.
        /// </summary>
        internal static string Reports_Column_CheckRiverOnBXLine {
            get {
                return ResourceManager.GetString("Reports_Column_CheckRiverOnBXLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call%.
        /// </summary>
        internal static string Reports_Column_ColdCall {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call 3-Bet%.
        /// </summary>
        internal static string Reports_Column_ColdCall_3Bet {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall_3Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call 4-Bet%.
        /// </summary>
        internal static string Reports_Column_ColdCall_4Bet {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall_4Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call BB%.
        /// </summary>
        internal static string Reports_Column_ColdCall_BB {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call BTN%.
        /// </summary>
        internal static string Reports_Column_ColdCall_BTN {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call CO%.
        /// </summary>
        internal static string Reports_Column_ColdCall_CO {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call EP%.
        /// </summary>
        internal static string Reports_Column_ColdCall_EP {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall_EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call MP%.
        /// </summary>
        internal static string Reports_Column_ColdCall_MP {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call SB%.
        /// </summary>
        internal static string Reports_Column_ColdCall_SB {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold call 3-Bet in BB%.
        /// </summary>
        internal static string Reports_Column_ColdCall3BetInBB {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall3BetInBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold call 3-Bet in BTN%.
        /// </summary>
        internal static string Reports_Column_ColdCall3BetInBTN {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall3BetInBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold call 3-Bet in CO%.
        /// </summary>
        internal static string Reports_Column_ColdCall3BetInCO {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall3BetInCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold call 3-Bet in MP%.
        /// </summary>
        internal static string Reports_Column_ColdCall3BetInMP {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall3BetInMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold call 3-Bet in SB%.
        /// </summary>
        internal static string Reports_Column_ColdCall3BetInSB {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall3BetInSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold call 4-Bet in BB%.
        /// </summary>
        internal static string Reports_Column_ColdCall4BetInBB {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall4BetInBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold call 4-Bet in BTN%.
        /// </summary>
        internal static string Reports_Column_ColdCall4BetInBTN {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall4BetInBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold call 4-Bet in CO%.
        /// </summary>
        internal static string Reports_Column_ColdCall4BetInCO {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall4BetInCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold call 4-Bet in MP%.
        /// </summary>
        internal static string Reports_Column_ColdCall4BetInMP {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall4BetInMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold call 4-Bet in SB%.
        /// </summary>
        internal static string Reports_Column_ColdCall4BetInSB {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCall4BetInSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call vs BTN open%.
        /// </summary>
        internal static string Reports_Column_ColdCallVsBTNOpen {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCallVsBTNOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call vs CO open%.
        /// </summary>
        internal static string Reports_Column_ColdCallVsCOOpen {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCallVsCOOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Call vs SB open%.
        /// </summary>
        internal static string Reports_Column_ColdCallVsSBOpen {
            get {
                return ResourceManager.GetString("Reports_Column_ColdCallVsSBOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed C-Bet%.
        /// </summary>
        internal static string Reports_Column_DelayedCBet {
            get {
                return ResourceManager.GetString("Reports_Column_DelayedCBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed Turn C-Bet in 3-Bet pot%.
        /// </summary>
        internal static string Reports_Column_DelayedTurnCBetIn3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_DelayedTurnCBetIn3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed Turn C-bet IP%.
        /// </summary>
        internal static string Reports_Column_DelayedTurnCBetIP {
            get {
                return ResourceManager.GetString("Reports_Column_DelayedTurnCBetIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed Turn C-bet OOP%.
        /// </summary>
        internal static string Reports_Column_DelayedTurnCBetOOP {
            get {
                return ResourceManager.GetString("Reports_Column_DelayedTurnCBetOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donk Bet%.
        /// </summary>
        internal static string Reports_Column_DonkBet {
            get {
                return ResourceManager.GetString("Reports_Column_DonkBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Barrel%.
        /// </summary>
        internal static string Reports_Column_DoubleBarrel {
            get {
                return ResourceManager.GetString("Reports_Column_DoubleBarrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Barrel 3-bet Pot%.
        /// </summary>
        internal static string Reports_Column_DoubleBarrel3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_DoubleBarrel3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Barrel SRP%.
        /// </summary>
        internal static string Reports_Column_DoubleBarrelSRP {
            get {
                return ResourceManager.GetString("Reports_Column_DoubleBarrelSRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Cards.
        /// </summary>
        internal static string Reports_Column_DownCards {
            get {
                return ResourceManager.GetString("Reports_Column_DownCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV bb/100.
        /// </summary>
        internal static string Reports_Column_EVBB100 {
            get {
                return ResourceManager.GetString("Reports_Column_EVBB100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $EV Diff.
        /// </summary>
        internal static string Reports_Column_EVDiff {
            get {
                return ResourceManager.GetString("Reports_Column_EVDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Tables.
        /// </summary>
        internal static string Reports_Column_FinalTables {
            get {
                return ResourceManager.GetString("Reports_Column_FinalTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float Flop%.
        /// </summary>
        internal static string Reports_Column_FloatFlop {
            get {
                return ResourceManager.GetString("Reports_Column_FloatFlop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float Flop then Bet Turn%.
        /// </summary>
        internal static string Reports_Column_FloatFlopThenBetTurn {
            get {
                return ResourceManager.GetString("Reports_Column_FloatFlopThenBetTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop AGG%.
        /// </summary>
        internal static string Reports_Column_FlopAgg {
            get {
                return ResourceManager.GetString("Reports_Column_FlopAgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop Bet%.
        /// </summary>
        internal static string Reports_Column_FlopBet {
            get {
                return ResourceManager.GetString("Reports_Column_FlopBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop Overbet Pot%.
        /// </summary>
        internal static string Reports_Column_FlopBetSizeMoreThanOne {
            get {
                return ResourceManager.GetString("Reports_Column_FlopBetSizeMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop Bet Size 1/2 or less%.
        /// </summary>
        internal static string Reports_Column_FlopBetSizeOneHalfOrLess {
            get {
                return ResourceManager.GetString("Reports_Column_FlopBetSizeOneHalfOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop Bet Size Pot Size or less%.
        /// </summary>
        internal static string Reports_Column_FlopBetSizeOneOrLess {
            get {
                return ResourceManager.GetString("Reports_Column_FlopBetSizeOneOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop Bet Size 1/4 or less%.
        /// </summary>
        internal static string Reports_Column_FlopBetSizeOneQuarterOrLess {
            get {
                return ResourceManager.GetString("Reports_Column_FlopBetSizeOneQuarterOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop Bet Size 3/4 or less%.
        /// </summary>
        internal static string Reports_Column_FlopBetSizeThreeQuartersOrLess {
            get {
                return ResourceManager.GetString("Reports_Column_FlopBetSizeThreeQuartersOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop Bet Size 2/3 or less%.
        /// </summary>
        internal static string Reports_Column_FlopBetSizeTwoThirdsOrLess {
            get {
                return ResourceManager.GetString("Reports_Column_FlopBetSizeTwoThirdsOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop Check Behind%.
        /// </summary>
        internal static string Reports_Column_FlopCheckBehind {
            get {
                return ResourceManager.GetString("Reports_Column_FlopCheckBehind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flop Check-Raise%.
        /// </summary>
        internal static string Reports_Column_FlopCheckRaise {
            get {
                return ResourceManager.GetString("Reports_Column_FlopCheckRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold BB vs. SB Steal%.
        /// </summary>
        internal static string Reports_Column_FoldBBvsSBSteal {
            get {
                return ResourceManager.GetString("Reports_Column_FoldBBvsSBSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to C-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldCBet {
            get {
                return ResourceManager.GetString("Reports_Column_FoldCBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold Flop%.
        /// </summary>
        internal static string Reports_Column_FoldFlop {
            get {
                return ResourceManager.GetString("Reports_Column_FoldFlop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3Bet {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet on BTN vs BB 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInBTNvs3BetBB {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInBTNvs3BetBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet on BTN vs SB 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInBTNvs3BetSB {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInBTNvs3BetSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet in CO vs BB 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInCOvs3BetBB {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInCOvs3BetBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet in CO vs BTN 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInCOvs3BetBTN {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInCOvs3BetBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet in CO vs SB 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInCOvs3BetSB {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInCOvs3BetSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet in EP vs BB 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInEPvs3BetBB {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInEPvs3BetBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet in EP vs BTN 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInEPvs3BetBTN {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInEPvs3BetBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet in EP vs CO 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInEPvs3BetCO {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInEPvs3BetCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet in EP vs MP 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInEPvs3BetMP {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInEPvs3BetMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet in EP vs SB 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInEPvs3BetSB {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInEPvs3BetSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet in MP vs BB 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInMPvs3BetBB {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInMPvs3BetBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet in MP vs BTN 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInMPvs3BetBTN {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInMPvs3BetBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet in MP vs CO 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInMPvs3BetCO {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInMPvs3BetCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet in MP vs SB 3-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetInMPvs3BetSB {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetInMPvs3BetSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet IP %.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetIP {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 3-Bet OOP %.
        /// </summary>
        internal static string Reports_Column_FoldTo3BetOOP {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo3BetOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 4-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo4Bet {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo4Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to 5-Bet%.
        /// </summary>
        internal static string Reports_Column_FoldTo5Bet {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTo5Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to C-Bet 3-Bet Pot%.
        /// </summary>
        internal static string Reports_Column_FoldToCBet3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToCBet3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to C-Bet 4-Bet Pot%.
        /// </summary>
        internal static string Reports_Column_FoldToCBet4BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToCBet4BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Raise &amp; Fold vs. Flop C-bet%.
        /// </summary>
        internal static string Reports_Column_FoldToCheckRaiseVsFlopCBet {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToCheckRaiseVsFlopCBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to Flop Donk Bet %.
        /// </summary>
        internal static string Reports_Column_FoldToDonkBet {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToDonkBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to Double Barrel%.
        /// </summary>
        internal static string Reports_Column_FoldToDoubleBarrel {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToDoubleBarrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to Double Barrell in 3-Bet Pot%.
        /// </summary>
        internal static string Reports_Column_FoldToDoubleBarrelIn3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToDoubleBarrelIn3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to Flop C-bet%.
        /// </summary>
        internal static string Reports_Column_FoldToFlopCBet {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToFlopCBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to Flop C-Bet IP%.
        /// </summary>
        internal static string Reports_Column_FoldToFlopCBetIP {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToFlopCBetIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to Flop C-Bet OOP%.
        /// </summary>
        internal static string Reports_Column_FoldToFlopCBetOOP {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToFlopCBetOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to Flop Check-Raise%.
        /// </summary>
        internal static string Reports_Column_FoldToFlopCheckRaise {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToFlopCheckRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to Flop Raise%.
        /// </summary>
        internal static string Reports_Column_FoldToFlopRaise {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToFlopRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to Triple Barrel%.
        /// </summary>
        internal static string Reports_Column_FoldToRiverCBet {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToRiverCBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to River Check-Raise%.
        /// </summary>
        internal static string Reports_Column_FoldToRiverCheckRaise {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToRiverCheckRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to river probe IP%.
        /// </summary>
        internal static string Reports_Column_FoldToRiverProbeIP {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToRiverProbeIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to River Raise%.
        /// </summary>
        internal static string Reports_Column_FoldToRiverRaise {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToRiverRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to Squeeze%.
        /// </summary>
        internal static string Reports_Column_FoldToSqueez {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToSqueez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to Turn Check-Raise%.
        /// </summary>
        internal static string Reports_Column_FoldToTurnCheckRaise {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToTurnCheckRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to turn probe IP%.
        /// </summary>
        internal static string Reports_Column_FoldToTurnProbeIP {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToTurnProbeIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold to Turn Raise%.
        /// </summary>
        internal static string Reports_Column_FoldToTurnRaise {
            get {
                return ResourceManager.GetString("Reports_Column_FoldToTurnRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold Turn%.
        /// </summary>
        internal static string Reports_Column_FoldTurn {
            get {
                return ResourceManager.GetString("Reports_Column_FoldTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Played.
        /// </summary>
        internal static string Reports_Column_GamesPlayed {
            get {
                return ResourceManager.GetString("Reports_Column_GamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Type.
        /// </summary>
        internal static string Reports_Column_GameType {
            get {
                return ResourceManager.GetString("Reports_Column_GameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour of Hand.
        /// </summary>
        internal static string Reports_Column_HourOfHand {
            get {
                return ResourceManager.GetString("Reports_Column_HourOfHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITM%.
        /// </summary>
        internal static string Reports_Column_ITM {
            get {
                return ResourceManager.GetString("Reports_Column_ITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp%.
        /// </summary>
        internal static string Reports_Column_Limp {
            get {
                return ResourceManager.GetString("Reports_Column_Limp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp BTN%.
        /// </summary>
        internal static string Reports_Column_Limp_BTN {
            get {
                return ResourceManager.GetString("Reports_Column_Limp_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp CO%.
        /// </summary>
        internal static string Reports_Column_Limp_CO {
            get {
                return ResourceManager.GetString("Reports_Column_Limp_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp EP%.
        /// </summary>
        internal static string Reports_Column_Limp_EP {
            get {
                return ResourceManager.GetString("Reports_Column_Limp_EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp MP%.
        /// </summary>
        internal static string Reports_Column_Limp_MP {
            get {
                return ResourceManager.GetString("Reports_Column_Limp_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp SB%.
        /// </summary>
        internal static string Reports_Column_Limp_SB {
            get {
                return ResourceManager.GetString("Reports_Column_Limp_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp Call%.
        /// </summary>
        internal static string Reports_Column_LimpCall {
            get {
                return ResourceManager.GetString("Reports_Column_LimpCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp Fold%.
        /// </summary>
        internal static string Reports_Column_LimpFold {
            get {
                return ResourceManager.GetString("Reports_Column_LimpFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limp Re-raise%.
        /// </summary>
        internal static string Reports_Column_LimpReRaise {
            get {
                return ResourceManager.GetString("Reports_Column_LimpReRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M-Ratio.
        /// </summary>
        internal static string Reports_Column_MRatio {
            get {
                return ResourceManager.GetString("Reports_Column_MRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Winnings.
        /// </summary>
        internal static string Reports_Column_NetWinnings {
            get {
                return ResourceManager.GetString("Reports_Column_NetWinnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Won.
        /// </summary>
        internal static string Reports_Column_NetWon {
            get {
                return ResourceManager.GetString("Reports_Column_NetWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR%.
        /// </summary>
        internal static string Reports_Column_PFR {
            get {
                return ResourceManager.GetString("Reports_Column_PFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR in BB%.
        /// </summary>
        internal static string Reports_Column_PFR_BB {
            get {
                return ResourceManager.GetString("Reports_Column_PFR_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR in BTN%.
        /// </summary>
        internal static string Reports_Column_PFR_BTN {
            get {
                return ResourceManager.GetString("Reports_Column_PFR_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR in CO%.
        /// </summary>
        internal static string Reports_Column_PFR_CO {
            get {
                return ResourceManager.GetString("Reports_Column_PFR_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR in EP%.
        /// </summary>
        internal static string Reports_Column_PFR_EP {
            get {
                return ResourceManager.GetString("Reports_Column_PFR_EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR in MP%.
        /// </summary>
        internal static string Reports_Column_PFR_MP {
            get {
                return ResourceManager.GetString("Reports_Column_PFR_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFR in SB%.
        /// </summary>
        internal static string Reports_Column_PFR_SB {
            get {
                return ResourceManager.GetString("Reports_Column_PFR_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string Reports_Column_Place {
            get {
                return ResourceManager.GetString("Reports_Column_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        internal static string Reports_Column_PlayerName {
            get {
                return ResourceManager.GetString("Reports_Column_PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player type.
        /// </summary>
        internal static string Reports_Column_PlayerType {
            get {
                return ResourceManager.GetString("Reports_Column_PlayerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poker Site.
        /// </summary>
        internal static string Reports_Column_PokerSite {
            get {
                return ResourceManager.GetString("Reports_Column_PokerSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Reports_Column_Position {
            get {
                return ResourceManager.GetString("Reports_Column_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe bet River%.
        /// </summary>
        internal static string Reports_Column_ProbeBetRiver {
            get {
                return ResourceManager.GetString("Reports_Column_ProbeBetRiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe bet Turn%.
        /// </summary>
        internal static string Reports_Column_ProbeBetTurn {
            get {
                return ResourceManager.GetString("Reports_Column_ProbeBetTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise C-Bet%.
        /// </summary>
        internal static string Reports_Column_RaiseCBet {
            get {
                return ResourceManager.GetString("Reports_Column_RaiseCBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Flop%.
        /// </summary>
        internal static string Reports_Column_RaiseFlop {
            get {
                return ResourceManager.GetString("Reports_Column_RaiseFlop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Flop C-Bet 3-Bet pot%.
        /// </summary>
        internal static string Reports_Column_RaiseFlopCBetIn3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_RaiseFlopCBetIn3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Frequency Factor%.
        /// </summary>
        internal static string Reports_Column_RaiseFreqFactor {
            get {
                return ResourceManager.GetString("Reports_Column_RaiseFreqFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Limpers%.
        /// </summary>
        internal static string Reports_Column_RaiseLimpers {
            get {
                return ResourceManager.GetString("Reports_Column_RaiseLimpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Limpers in BB%.
        /// </summary>
        internal static string Reports_Column_RaiseLimpersInBB {
            get {
                return ResourceManager.GetString("Reports_Column_RaiseLimpersInBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Limpers on BTN%.
        /// </summary>
        internal static string Reports_Column_RaiseLimpersInBN {
            get {
                return ResourceManager.GetString("Reports_Column_RaiseLimpersInBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Limpers in CO%.
        /// </summary>
        internal static string Reports_Column_RaiseLimpersInCO {
            get {
                return ResourceManager.GetString("Reports_Column_RaiseLimpersInCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Limpers in MP%.
        /// </summary>
        internal static string Reports_Column_RaiseLimpersInMP {
            get {
                return ResourceManager.GetString("Reports_Column_RaiseLimpersInMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Limpers in SB%.
        /// </summary>
        internal static string Reports_Column_RaiseLimpersInSB {
            get {
                return ResourceManager.GetString("Reports_Column_RaiseLimpersInSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise River%.
        /// </summary>
        internal static string Reports_Column_RaiseRiver {
            get {
                return ResourceManager.GetString("Reports_Column_RaiseRiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Turn%.
        /// </summary>
        internal static string Reports_Column_RaiseTurn {
            get {
                return ResourceManager.GetString("Reports_Column_RaiseTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rake.
        /// </summary>
        internal static string Reports_Column_Rake {
            get {
                return ResourceManager.GetString("Reports_Column_Rake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-buy.
        /// </summary>
        internal static string Reports_Column_Rebuy {
            get {
                return ResourceManager.GetString("Reports_Column_Rebuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River AGG%.
        /// </summary>
        internal static string Reports_Column_RiverAgg {
            get {
                return ResourceManager.GetString("Reports_Column_RiverAgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Bet %.
        /// </summary>
        internal static string Reports_Column_RiverBet {
            get {
                return ResourceManager.GetString("Reports_Column_RiverBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Overbet Pot%.
        /// </summary>
        internal static string Reports_Column_RiverBetSizeMoreThanOne {
            get {
                return ResourceManager.GetString("Reports_Column_RiverBetSizeMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Call Efficiency.
        /// </summary>
        internal static string Reports_Column_RiverCallEffeciency {
            get {
                return ResourceManager.GetString("Reports_Column_RiverCallEffeciency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Check/Call%.
        /// </summary>
        internal static string Reports_Column_RiverCheckCall {
            get {
                return ResourceManager.GetString("Reports_Column_RiverCheckCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Check/Fold%.
        /// </summary>
        internal static string Reports_Column_RiverCheckFold {
            get {
                return ResourceManager.GetString("Reports_Column_RiverCheckFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROI%.
        /// </summary>
        internal static string Reports_Column_ROI {
            get {
                return ResourceManager.GetString("Reports_Column_ROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen River%.
        /// </summary>
        internal static string Reports_Column_SeenRiver {
            get {
                return ResourceManager.GetString("Reports_Column_SeenRiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen Turn%.
        /// </summary>
        internal static string Reports_Column_SeenTurn {
            get {
                return ResourceManager.GetString("Reports_Column_SeenTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Length.
        /// </summary>
        internal static string Reports_Column_SessionLength {
            get {
                return ResourceManager.GetString("Reports_Column_SessionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Start.
        /// </summary>
        internal static string Reports_Column_SessionStart {
            get {
                return ResourceManager.GetString("Reports_Column_SessionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shove flop after 4-betting pre-flop%.
        /// </summary>
        internal static string Reports_Column_ShovedFlopAfter4Bet {
            get {
                return ResourceManager.GetString("Reports_Column_ShovedFlopAfter4Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showdown Hand.
        /// </summary>
        internal static string Reports_Column_ShowdownHand {
            get {
                return ResourceManager.GetString("Reports_Column_ShowdownHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Reports_Column_Speed {
            get {
                return ResourceManager.GetString("Reports_Column_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squeeze%.
        /// </summary>
        internal static string Reports_Column_Squeeze {
            get {
                return ResourceManager.GetString("Reports_Column_Squeeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Reports_Column_Started {
            get {
                return ResourceManager.GetString("Reports_Column_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Std dev.
        /// </summary>
        internal static string Reports_Column_StdDev {
            get {
                return ResourceManager.GetString("Reports_Column_StdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Std dev in bb.
        /// </summary>
        internal static string Reports_Column_StdDevBB {
            get {
                return ResourceManager.GetString("Reports_Column_StdDevBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Std dev in bb/100.
        /// </summary>
        internal static string Reports_Column_StdDevBB100 {
            get {
                return ResourceManager.GetString("Reports_Column_StdDevBB100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steal%.
        /// </summary>
        internal static string Reports_Column_Steal {
            get {
                return ResourceManager.GetString("Reports_Column_Steal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Size.
        /// </summary>
        internal static string Reports_Column_TableSize {
            get {
                return ResourceManager.GetString("Reports_Column_TableSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Type.
        /// </summary>
        internal static string Reports_Column_TableType {
            get {
                return ResourceManager.GetString("Reports_Column_TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BB vs BTN%.
        /// </summary>
        internal static string Reports_Column_ThreeBetBBvsBTN {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetBBvsBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BB vs CO%.
        /// </summary>
        internal static string Reports_Column_ThreeBetBBvsCO {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetBBvsCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BB vs EP%.
        /// </summary>
        internal static string Reports_Column_ThreeBetBBvsEP {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetBBvsEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BB vs MP%.
        /// </summary>
        internal static string Reports_Column_ThreeBetBBvsMP {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetBBvsMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BB vs SB%.
        /// </summary>
        internal static string Reports_Column_ThreeBetBBvsSB {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetBBvsSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BTN vs CO%.
        /// </summary>
        internal static string Reports_Column_ThreeBetBTNvsCO {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetBTNvsCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BTN vs EP%.
        /// </summary>
        internal static string Reports_Column_ThreeBetBTNvsEP {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetBTNvsEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet BTN vs MP%.
        /// </summary>
        internal static string Reports_Column_ThreeBetBTNvsMP {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetBTNvsMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet CO vs EP%.
        /// </summary>
        internal static string Reports_Column_ThreeBetCOvsEP {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetCOvsEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet CO vs MP%.
        /// </summary>
        internal static string Reports_Column_ThreeBetCOvsMP {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetCOvsMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet MP vs EP%.
        /// </summary>
        internal static string Reports_Column_ThreeBetMPvsEP {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetMPvsEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet SB vs BTN%.
        /// </summary>
        internal static string Reports_Column_ThreeBetSBvsBTN {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetSBvsBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet SB vs CO%.
        /// </summary>
        internal static string Reports_Column_ThreeBetSBvsCO {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetSBvsCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet SB vs EP%.
        /// </summary>
        internal static string Reports_Column_ThreeBetSBvsEP {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetSBvsEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Bet SB vs MP%.
        /// </summary>
        internal static string Reports_Column_ThreeBetSBvsMP {
            get {
                return ResourceManager.GetString("Reports_Column_ThreeBetSBvsMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hands.
        /// </summary>
        internal static string Reports_Column_TotalHands {
            get {
                return ResourceManager.GetString("Reports_Column_TotalHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Winnings.
        /// </summary>
        internal static string Reports_Column_TotalWinnings {
            get {
                return ResourceManager.GetString("Reports_Column_TotalWinnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Won.
        /// </summary>
        internal static string Reports_Column_TotalWon {
            get {
                return ResourceManager.GetString("Reports_Column_TotalWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament Length.
        /// </summary>
        internal static string Reports_Column_TournamentLength {
            get {
                return ResourceManager.GetString("Reports_Column_TournamentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple Barrel%.
        /// </summary>
        internal static string Reports_Column_TripleBarrel {
            get {
                return ResourceManager.GetString("Reports_Column_TripleBarrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple Barrel 3-bet Pot%.
        /// </summary>
        internal static string Reports_Column_TripleBarrel3BetPot {
            get {
                return ResourceManager.GetString("Reports_Column_TripleBarrel3BetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple Barrel SRP%.
        /// </summary>
        internal static string Reports_Column_TripleBarrelSRP {
            get {
                return ResourceManager.GetString("Reports_Column_TripleBarrelSRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Aggression% (TAP).
        /// </summary>
        internal static string Reports_Column_TrueAgg {
            get {
                return ResourceManager.GetString("Reports_Column_TrueAgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn AF.
        /// </summary>
        internal static string Reports_Column_TurnAF {
            get {
                return ResourceManager.GetString("Reports_Column_TurnAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn AGG%.
        /// </summary>
        internal static string Reports_Column_TurnAgg {
            get {
                return ResourceManager.GetString("Reports_Column_TurnAgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Bet%.
        /// </summary>
        internal static string Reports_Column_TurnBet {
            get {
                return ResourceManager.GetString("Reports_Column_TurnBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Overbet Pot%.
        /// </summary>
        internal static string Reports_Column_TurnBetSizeMoreThanOne {
            get {
                return ResourceManager.GetString("Reports_Column_TurnBetSizeMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Bet Size 1/2 or less%.
        /// </summary>
        internal static string Reports_Column_TurnBetSizeOneHalfOrLess {
            get {
                return ResourceManager.GetString("Reports_Column_TurnBetSizeOneHalfOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Bet Size Pot Size or less%.
        /// </summary>
        internal static string Reports_Column_TurnBetSizeOneOrLess {
            get {
                return ResourceManager.GetString("Reports_Column_TurnBetSizeOneOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Bet Size 1/4 or less%.
        /// </summary>
        internal static string Reports_Column_TurnBetSizeOneQuarterOrLess {
            get {
                return ResourceManager.GetString("Reports_Column_TurnBetSizeOneQuarterOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Bet Size 1/3 or less%.
        /// </summary>
        internal static string Reports_Column_TurnBetSizeOneThirdOrLess {
            get {
                return ResourceManager.GetString("Reports_Column_TurnBetSizeOneThirdOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Bet Size 3/4 or less%.
        /// </summary>
        internal static string Reports_Column_TurnBetSizeThreeQuartersOrLess {
            get {
                return ResourceManager.GetString("Reports_Column_TurnBetSizeThreeQuartersOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Bet Size 2/3 or less%.
        /// </summary>
        internal static string Reports_Column_TurnBetSizeTwoThirdsOrLess {
            get {
                return ResourceManager.GetString("Reports_Column_TurnBetSizeTwoThirdsOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Check-Raise%.
        /// </summary>
        internal static string Reports_Column_TurnCheckRaise {
            get {
                return ResourceManager.GetString("Reports_Column_TurnCheckRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO-PFR BB%.
        /// </summary>
        internal static string Reports_Column_UO_PFR_BB {
            get {
                return ResourceManager.GetString("Reports_Column_UO_PFR_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO-PFR BTN%.
        /// </summary>
        internal static string Reports_Column_UO_PFR_BTN {
            get {
                return ResourceManager.GetString("Reports_Column_UO_PFR_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO-PFR CO%.
        /// </summary>
        internal static string Reports_Column_UO_PFR_CO {
            get {
                return ResourceManager.GetString("Reports_Column_UO_PFR_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO-PFR EP%.
        /// </summary>
        internal static string Reports_Column_UO_PFR_EP {
            get {
                return ResourceManager.GetString("Reports_Column_UO_PFR_EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO-PFR MP%.
        /// </summary>
        internal static string Reports_Column_UO_PFR_MP {
            get {
                return ResourceManager.GetString("Reports_Column_UO_PFR_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO-PFR SB%.
        /// </summary>
        internal static string Reports_Column_UO_PFR_SB {
            get {
                return ResourceManager.GetString("Reports_Column_UO_PFR_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $/h.
        /// </summary>
        internal static string Reports_Column_UsdPerHour {
            get {
                return ResourceManager.GetString("Reports_Column_UsdPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP%.
        /// </summary>
        internal static string Reports_Column_VPIP {
            get {
                return ResourceManager.GetString("Reports_Column_VPIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP BB%.
        /// </summary>
        internal static string Reports_Column_VPIP_BB {
            get {
                return ResourceManager.GetString("Reports_Column_VPIP_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP BTN%.
        /// </summary>
        internal static string Reports_Column_VPIP_BTN {
            get {
                return ResourceManager.GetString("Reports_Column_VPIP_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP CO%.
        /// </summary>
        internal static string Reports_Column_VPIP_CO {
            get {
                return ResourceManager.GetString("Reports_Column_VPIP_CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP EP%.
        /// </summary>
        internal static string Reports_Column_VPIP_EP {
            get {
                return ResourceManager.GetString("Reports_Column_VPIP_EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP MP%.
        /// </summary>
        internal static string Reports_Column_VPIP_MP {
            get {
                return ResourceManager.GetString("Reports_Column_VPIP_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPIP SB%.
        /// </summary>
        internal static string Reports_Column_VPIP_SB {
            get {
                return ResourceManager.GetString("Reports_Column_VPIP_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning%.
        /// </summary>
        internal static string Reports_Column_Winning {
            get {
                return ResourceManager.GetString("Reports_Column_Winning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won Amount.
        /// </summary>
        internal static string Reports_Column_WonAmount {
            get {
                return ResourceManager.GetString("Reports_Column_WonAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won%.
        /// </summary>
        internal static string Reports_Column_WonPercent {
            get {
                return ResourceManager.GetString("Reports_Column_WonPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W$SD.
        /// </summary>
        internal static string Reports_Column_WSSD {
            get {
                return ResourceManager.GetString("Reports_Column_WSSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W$WSF.
        /// </summary>
        internal static string Reports_Column_WSWSF {
            get {
                return ResourceManager.GetString("Reports_Column_WSWSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTSD%.
        /// </summary>
        internal static string Reports_Column_WTSD {
            get {
                return ResourceManager.GetString("Reports_Column_WTSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTSD% after calling 3-Bet PF%.
        /// </summary>
        internal static string Reports_Column_WTSDAfterCalling3Bet {
            get {
                return ResourceManager.GetString("Reports_Column_WTSDAfterCalling3Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTSD% after calling PFR%.
        /// </summary>
        internal static string Reports_Column_WTSDAfterCallingPfr {
            get {
                return ResourceManager.GetString("Reports_Column_WTSDAfterCallingPfr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTSD% after not C-Betting flop as PFR%.
        /// </summary>
        internal static string Reports_Column_WTSDAfterNotCBettingFlopAsPfr {
            get {
                return ResourceManager.GetString("Reports_Column_WTSDAfterNotCBettingFlopAsPfr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTSD% after seeing Turn%.
        /// </summary>
        internal static string Reports_Column_WTSDAfterSeeingTurn {
            get {
                return ResourceManager.GetString("Reports_Column_WTSDAfterSeeingTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTSD% as PF 3-Bettor%.
        /// </summary>
        internal static string Reports_Column_WTSDAsPF3Bettor {
            get {
                return ResourceManager.GetString("Reports_Column_WTSDAsPF3Bettor", resourceCulture);
            }
        }
    }
}
