//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveHUD.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveHUD.Common.Resources.SystemSettings", typeof(SystemSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentPlayer.txt.
        /// </summary>
        internal static string SystemSettings_ActivePlayerFileName {
            get {
                return ResourceManager.GetString("SystemSettings_ActivePlayerFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drivehud.com.
        /// </summary>
        internal static string SystemSettings_AddActivationLink {
            get {
                return ResourceManager.GetString("SystemSettings_AddActivationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveHUD.
        /// </summary>
        internal static string SystemSettings_AppDataFolder {
            get {
                return ResourceManager.GetString("SystemSettings_AppDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppStore.
        /// </summary>
        internal static string SystemSettings_AppStoreDataFolder {
            get {
                return ResourceManager.GetString("SystemSettings_AppStoreDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.xml.
        /// </summary>
        internal static string SystemSettings_AppStoreLocalProductRepo {
            get {
                return ResourceManager.GetString("SystemSettings_AppStoreLocalProductRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.tmp.
        /// </summary>
        internal static string SystemSettings_AppStoreLocalTempProductRepo {
            get {
                return ResourceManager.GetString("SystemSettings_AppStoreLocalTempProductRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to training.tmp.
        /// </summary>
        internal static string SystemSettings_AppStoreLocalTempTrainingProductRepo {
            get {
                return ResourceManager.GetString("SystemSettings_AppStoreLocalTempTrainingProductRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to training.xml.
        /// </summary>
        internal static string SystemSettings_AppStoreLocalTrainingProductRepo {
            get {
                return ResourceManager.GetString("SystemSettings_AppStoreLocalTrainingProductRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drivehud.com/appstore/products.hash.
        /// </summary>
        internal static string SystemSettings_AppStoreRemoteProductHash {
            get {
                return ResourceManager.GetString("SystemSettings_AppStoreRemoteProductHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drivehud.com/appstore/products.xml.
        /// </summary>
        internal static string SystemSettings_AppStoreRemoteProductRepo {
            get {
                return ResourceManager.GetString("SystemSettings_AppStoreRemoteProductRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drivehud.com/appstore/training.hash.
        /// </summary>
        internal static string SystemSettings_AppStoreRemoteTrainingProductHash {
            get {
                return ResourceManager.GetString("SystemSettings_AppStoreRemoteTrainingProductHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drivehud.com/appstore/training.xml.
        /// </summary>
        internal static string SystemSettings_AppStoreRemoteTrainingProductRepo {
            get {
                return ResourceManager.GetString("SystemSettings_AppStoreRemoteTrainingProductRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drivehud.db.
        /// </summary>
        internal static string SystemSettings_DbFileName {
            get {
                return ResourceManager.GetString("SystemSettings_DbFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string SystemSettings_DefaultPlayersFolderName {
            get {
                return ResourceManager.GetString("SystemSettings_DefaultPlayersFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .stat.
        /// </summary>
        internal static string SystemSettings_DefaultPlayerStatisticExtension {
            get {
                return ResourceManager.GetString("SystemSettings_DefaultPlayerStatisticExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string SystemSettings_DefaultPlayerStatisticFolderName {
            get {
                return ResourceManager.GetString("SystemSettings_DefaultPlayerStatisticFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drivehud.com/blog/forums/.
        /// </summary>
        internal static string SystemSettings_ForumsLink {
            get {
                return ResourceManager.GetString("SystemSettings_ForumsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero.
        /// </summary>
        internal static string SystemSettings_HeroName {
            get {
                return ResourceManager.GetString("SystemSettings_HeroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drivehud.com/blog/knowledgebase/.
        /// </summary>
        internal static string SystemSettings_KnowledgeBase {
            get {
                return ResourceManager.GetString("SystemSettings_KnowledgeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        internal static string SystemSettings_LayoutsExtension {
            get {
                return ResourceManager.GetString("SystemSettings_LayoutsExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layouts.
        /// </summary>
        internal static string SystemSettings_LayoutsFolder {
            get {
                return ResourceManager.GetString("SystemSettings_LayoutsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappings.
        /// </summary>
        internal static string SystemSettings_LayoutsMappings {
            get {
                return ResourceManager.GetString("SystemSettings_LayoutsMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LayoutsV2.
        /// </summary>
        internal static string SystemSettings_LayoutsV2Folder {
            get {
                return ResourceManager.GetString("SystemSettings_LayoutsV2Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string SystemSettings_LogsFolder {
            get {
                return ResourceManager.GetString("SystemSettings_LogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drivehud.com/blog/manual/.
        /// </summary>
        internal static string SystemSettings_OnlineManual {
            get {
                return ResourceManager.GetString("SystemSettings_OnlineManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database-backup.
        /// </summary>
        internal static string SystemSettings_PlayerStatisticBackupFolderName {
            get {
                return ResourceManager.GetString("SystemSettings_PlayerStatisticBackupFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database-old.
        /// </summary>
        internal static string SystemSettings_PlayerStatisticOldFolderName {
            get {
                return ResourceManager.GetString("SystemSettings_PlayerStatisticOldFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database-temp.
        /// </summary>
        internal static string SystemSettings_PlayerStatisticTempFolderName {
            get {
                return ResourceManager.GetString("SystemSettings_PlayerStatisticTempFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drivehud.com/pricing.
        /// </summary>
        internal static string SystemSettings_PricingLink {
            get {
                return ResourceManager.GetString("SystemSettings_PricingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.acepokersolutions.com/index.php?route=checkout/renewal&amp;code={0}.
        /// </summary>
        internal static string SystemSettings_RenewLicenseLink {
            get {
                return ResourceManager.GetString("SystemSettings_RenewLicenseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drivehud.com/blog/manual/#document-21.
        /// </summary>
        internal static string SystemSettings_SiteSetup_PokerStars {
            get {
                return ResourceManager.GetString("SystemSettings_SiteSetup_PokerStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@drivehud.com.
        /// </summary>
        internal static string SystemSettings_SupportEmail {
            get {
                return ResourceManager.GetString("SystemSettings_SupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0}
        ///
        ///{1}.
        /// </summary>
        internal static string SystemSettings_SupportMessageBody {
            get {
                return ResourceManager.GetString("SystemSettings_SupportMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.5.3.
        /// </summary>
        internal static string SystemSettings_TargetDatabaseVersion {
            get {
                return ResourceManager.GetString("SystemSettings_TargetDatabaseVersion", resourceCulture);
            }
        }
    }
}
