//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveHUD.Bootstrapper.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveHUD.Bootstrapper.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action canceled..
        /// </summary>
        internal static string strActionCanceled {
            get {
                return ResourceManager.GetString("strActionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling....
        /// </summary>
        internal static string strCanceling {
            get {
                return ResourceManager.GetString("strCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation state is unknown..
        /// </summary>
        internal static string strInstallationStateUnknown {
            get {
                return ResourceManager.GetString("strInstallationStateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete..
        /// </summary>
        internal static string strInstallComplete {
            get {
                return ResourceManager.GetString("strInstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        internal static string strInstalling {
            get {
                return ResourceManager.GetString("strInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree the license term before you can install {0}..
        /// </summary>
        internal static string strInstallLicenseTerms {
            get {
                return ResourceManager.GetString("strInstallLicenseTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for installing {0}!.
        /// </summary>
        internal static string strInstallThankyou {
            get {
                return ResourceManager.GetString("strInstallThankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring your computer.
        /// </summary>
        internal static string strMessageInitialize {
            get {
                return ResourceManager.GetString("strMessageInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while setup cancels the installation.
        ///This may take a few minutes...
        /// </summary>
        internal static string strPleaseWaitWhileCanceling {
            get {
                return ResourceManager.GetString("strPleaseWaitWhileCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while setup installs {0} on your computer. 
        ///This may take a few minutes...
        /// </summary>
        internal static string strPleaseWaitWhileInstalling {
            get {
                return ResourceManager.GetString("strPleaseWaitWhileInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while setup repairs {0} on your computer.
        ///This may take a few minutes...
        /// </summary>
        internal static string strPleaseWaitWhileRepairing {
            get {
                return ResourceManager.GetString("strPleaseWaitWhileRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while setup uninstalls {0} from your computer.
        ///This may take a few minutes...
        /// </summary>
        internal static string strPleaseWaitWhileUninstalling {
            get {
                return ResourceManager.GetString("strPleaseWaitWhileUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair complete..
        /// </summary>
        internal static string strRepairComplete {
            get {
                return ResourceManager.GetString("strRepairComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing....
        /// </summary>
        internal static string strRepairing {
            get {
                return ResourceManager.GetString("strRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using {0}!.
        /// </summary>
        internal static string strRepairThankyou {
            get {
                return ResourceManager.GetString("strRepairThankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall complete..
        /// </summary>
        internal static string strUninstallComplete {
            get {
                return ResourceManager.GetString("strUninstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        internal static string strUninstalling {
            get {
                return ResourceManager.GetString("strUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using {0}!.
        /// </summary>
        internal static string strUninstallThankyou {
            get {
                return ResourceManager.GetString("strUninstallThankyou", resourceCulture);
            }
        }
    }
}
