
C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe -d"DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\\" 

-dSolutionDir=D:\AcePokerSolutions\DriveHUD\trunk\src\ 
-dSolutionExt=.sln 
-dSolutionFileName=DriveHUD.sln 
-dSolutionName=DriveHUD 
-dSolutionPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.sln 
-dConfiguration=Release 
-dOutDir=bin\Release\ 
-dPlatform=x86 
-dProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Setup\ 
-dProjectExt=.wixproj -dProjectFileName=DriveHUD.Setup.wixproj 
-dProjectName=DriveHUD.Setup 
-dProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Setup\DriveHUD.Setup.wixproj 
-dTargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Setup\bin\Release\ 
-dTargetExt=.msi 
-dTargetFileName=DriveHUD.msi 
-dTargetName=DriveHUD 
-dTargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Setup\bin\Release\DriveHUD.msi 
-dDriveHUD.Application.Configuration=Release -d"DriveHUD.Application.FullConfiguration=Release|AnyCPU" 
-dDriveHUD.Application.Platform=AnyCPU -dDriveHUD.Application.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Application\ 
-dDriveHUD.Application.ProjectExt=.csproj -dDriveHUD.Application.ProjectFileName=DriveHUD.Application.csproj 
-dDriveHUD.Application.ProjectName=DriveHUD.Application 
-dDriveHUD.Application.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Application\DriveHUD.Application.csproj 
-dDriveHUD.Application.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Application\bin\Release\
-dDriveHUD.Application.TargetExt=.exe 
-dDriveHUD.Application.TargetFileName=DriveHUD.Application.exe 
-dDriveHUD.Application.TargetName=DriveHUD.Application 
-dDriveHUD.Application.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Application\bin\Release\DriveHUD.Application.exe 
-dDriveHUD.Common.Infrastructure.Configuration=Release 
-d"DriveHUD.Common.Infrastructure.FullConfiguration=Release|AnyCPU" 
-dDriveHUD.Common.Infrastructure.Platform=AnyCPU 
-dDriveHUD.Common.Infrastructure.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common.Infrastructure\ 
-dDriveHUD.Common.Infrastructure.ProjectExt=.csproj 
-dDriveHUD.Common.Infrastructure.ProjectFileName=DriveHUD.Common.Infrastructure.csproj 
-dDriveHUD.Common.Infrastructure.ProjectName=DriveHUD.Common.Infrastructure 
-dDriveHUD.Common.Infrastructure.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common.Infrastructure\DriveHUD.Common.Infrastructure.csproj 
-dDriveHUD.Common.Infrastructure.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common.Infrastructure\bin\Release\ 
-dDriveHUD.Common.Infrastructure.TargetExt=.dll 
-dDriveHUD.Common.Infrastructure.TargetFileName=DriveHUD.Common.Infrastructure.dll 
-dDriveHUD.Common.Infrastructure.TargetName=DriveHUD.Common.Infrastructure 
-dDriveHUD.Common.Infrastructure.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common.Infrastructure\bin\Release\DriveHUD.Common.Infrastructure.dll 
-dDriveHUD.Common.Resources.Configuration=Release 
-d"DriveHUD.Common.Resources.FullConfiguration=Release|AnyCPU" 
-dDriveHUD.Common.Resources.Platform=AnyCPU 
-dDriveHUD.Common.Resources.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common.Resources\ 
-dDriveHUD.Common.Resources.ProjectExt=.csproj 
-dDriveHUD.Common.Resources.ProjectFileName=DriveHUD.Common.Resources.csproj 
-dDriveHUD.Common.Resources.ProjectName=DriveHUD.Common.Resources 
-dDriveHUD.Common.Resources.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common.Resources\DriveHUD.Common.Resources.csproj 
-dDriveHUD.Common.Resources.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common.Resources\bin\Release\ 
-dDriveHUD.Common.Resources.TargetExt=.dll 
-dDriveHUD.Common.Resources.TargetFileName=DriveHUD.Common.Resources.dll 
-dDriveHUD.Common.Resources.TargetName=DriveHUD.Common.Resources 
-dDriveHUD.Common.Resources.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common.Resources\bin\Release\DriveHUD.Common.Resources.dll 
-dDriveHUD.Common.Wpf.Configuration=Release
 -d"DriveHUD.Common.Wpf.FullConfiguration=Release|AnyCPU" 
 -dDriveHUD.Common.Wpf.Platform=AnyCPU 
 -dDriveHUD.Common.Wpf.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common.Wpf\ 
 -dDriveHUD.Common.Wpf.ProjectExt=.csproj 
 -dDriveHUD.Common.Wpf.ProjectFileName=DriveHUD.Common.Wpf.csproj 
 -dDriveHUD.Common.Wpf.ProjectName=DriveHUD.Common.Wpf 
 -dDriveHUD.Common.Wpf.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common.Wpf\DriveHUD.Common.Wpf.csproj 
 -dDriveHUD.Common.Wpf.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common.Wpf\bin\Release\ 
 -dDriveHUD.Common.Wpf.TargetExt=.dll 
 -dDriveHUD.Common.Wpf.TargetFileName=DriveHUD.Common.Wpf.dll 
 -dDriveHUD.Common.Wpf.TargetName=DriveHUD.Common.Wpf 
 -dDriveHUD.Common.Wpf.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common.Wpf\bin\Release\DriveHUD.Common.Wpf.dll 
 -dDriveHUD.Common.Configuration=Release -d"DriveHUD.Common.FullConfiguration=Release|AnyCPU" 
 -dDriveHUD.Common.Platform=AnyCPU 
 -dDriveHUD.Common.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common\ 
 -dDriveHUD.Common.ProjectExt=.csproj 
 -dDriveHUD.Common.ProjectFileName=DriveHUD.Common.csproj 
 -dDriveHUD.Common.ProjectName=DriveHUD.Common 
 -dDriveHUD.Common.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common\DriveHUD.Common.csproj 
 -dDriveHUD.Common.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common\bin\Release\ 
 -dDriveHUD.Common.TargetExt=.dll 
 -dDriveHUD.Common.TargetFileName=DriveHUD.Common.dll 
 -dDriveHUD.Common.TargetName=DriveHUD.Common 
 -dDriveHUD.Common.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Common\bin\Release\DriveHUD.Common.dll 
 -dDriveHUD.Controls.Configuration=Release -d"DriveHUD.Controls.FullConfiguration=Release|AnyCPU" 
 -dDriveHUD.Controls.Platform=AnyCPU 
 -dDriveHUD.Controls.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Controls\ 
 -dDriveHUD.Controls.ProjectExt=.csproj 
 -dDriveHUD.Controls.ProjectFileName=DriveHUD.Controls.csproj 
 -dDriveHUD.Controls.ProjectName=DriveHUD.Controls 
 -dDriveHUD.Controls.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Controls\DriveHUD.Controls.csproj 
 -dDriveHUD.Controls.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Controls\bin\Release\ 
 -dDriveHUD.Controls.TargetExt=.dll 
 -dDriveHUD.Controls.TargetFileName=DriveHUD.Controls.dll 
 -dDriveHUD.Controls.TargetName=DriveHUD.Controls 
 -dDriveHUD.Controls.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Controls\bin\Release\DriveHUD.Controls.dll 
 -dDriveHUD.DBMigrator.Configuration=Release -d"DriveHUD.DBMigrator.FullConfiguration=Release|AnyCPU" 
 -dDriveHUD.DBMigrator.Platform=AnyCPU 
 -dDriveHUD.DBMigrator.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.DBMigrator\ 
 -dDriveHUD.DBMigrator.ProjectExt=.csproj 
 -dDriveHUD.DBMigrator.ProjectFileName=DriveHUD.DBMigrator.csproj 
 -dDriveHUD.DBMigrator.ProjectName=DriveHUD.DBMigrator 
 -dDriveHUD.DBMigrator.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.DBMigrator\DriveHUD.DBMigrator.csproj 
 -dDriveHUD.DBMigrator.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.DBMigrator\bin\Release\ 
 -dDriveHUD.DBMigrator.TargetExt=.dll 
 -dDriveHUD.DBMigrator.TargetFileName=DriveHUD.DBMigrator.dll 
 -dDriveHUD.DBMigrator.TargetName=DriveHUD.DBMigrator 
 -dDriveHUD.DBMigrator.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.DBMigrator\bin\Release\DriveHUD.DBMigrator.dll 
 -dDriveHUD.Entities.Configuration=Release -d"DriveHUD.Entities.FullConfiguration=Release|AnyCPU" 
 -dDriveHUD.Entities.Platform=AnyCPU 
 -dDriveHUD.Entities.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Entities\ 
 -dDriveHUD.Entities.ProjectExt=.csproj 
 -dDriveHUD.Entities.ProjectFileName=DriveHUD.Entities.csproj 
 -dDriveHUD.Entities.ProjectName=DriveHUD.Entities 
 -dDriveHUD.Entities.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Entities\DriveHUD.Entities.csproj 
 -dDriveHUD.Entities.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Entities\bin\Release\ 
 -dDriveHUD.Entities.TargetExt=.dll 
 -dDriveHUD.Entities.TargetFileName=DriveHUD.Entities.dll 
 -dDriveHUD.Entities.TargetName=DriveHUD.Entities 
 -dDriveHUD.Entities.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Entities\bin\Release\DriveHUD.Entities.dll 
 -dDriveHUD.EquityCalculator.Configuration=Release 
 -d"DriveHUD.EquityCalculator.FullConfiguration=Release|AnyCPU" 
 -dDriveHUD.EquityCalculator.Platform=AnyCPU 
 -dDriveHUD.EquityCalculator.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.EquityCalculator\ 
 -dDriveHUD.EquityCalculator.ProjectExt=.csproj 
 -dDriveHUD.EquityCalculator.ProjectFileName=DriveHUD.EquityCalculator.csproj 
 -dDriveHUD.EquityCalculator.ProjectName=DriveHUD.EquityCalculator 
 -dDriveHUD.EquityCalculator.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.EquityCalculator\DriveHUD.EquityCalculator.csproj 
 -dDriveHUD.EquityCalculator.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.EquityCalculator\bin\Release\ 
 -dDriveHUD.EquityCalculator.TargetExt=.dll 
 -dDriveHUD.EquityCalculator.TargetFileName=DriveHUD.EquityCalculator.dll 
 -dDriveHUD.EquityCalculator.TargetName=DriveHUD.EquityCalculator 
 -dDriveHUD.EquityCalculator.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.EquityCalculator\bin\Release\DriveHUD.EquityCalculator.dll 
 -dDriveHUD.Importers.Configuration=Release -d"DriveHUD.Importers.FullConfiguration=Release|AnyCPU" 
 -dDriveHUD.Importers.Platform=AnyCPU 
 -dDriveHUD.Importers.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Importer\ 
 -dDriveHUD.Importers.ProjectExt=.csproj 
 -dDriveHUD.Importers.ProjectFileName=DriveHUD.Importers.csproj 
 -dDriveHUD.Importers.ProjectName=DriveHUD.Importers 
 -dDriveHUD.Importers.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Importer\DriveHUD.Importers.csproj 
 -dDriveHUD.Importers.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Importer\bin\Release\ 
 -dDriveHUD.Importers.TargetExt=.dll 
 -dDriveHUD.Importers.TargetFileName=DriveHUD.Importers.dll 
 -dDriveHUD.Importers.TargetName=DriveHUD.Importers 
 -dDriveHUD.Importers.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Importer\bin\Release\DriveHUD.Importers.dll 
 -dDriveHUD.Inserter.Configuration=Release -d"DriveHUD.Inserter.FullConfiguration=Release|AnyCPU" 
 -dDriveHUD.Inserter.Platform=AnyCPU 
 -dDriveHUD.Inserter.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Inserter\ 
 -dDriveHUD.Inserter.ProjectExt=.csproj 
 -dDriveHUD.Inserter.ProjectFileName=DriveHUD.Inserter.csproj 
 -dDriveHUD.Inserter.ProjectName=DriveHUD.Inserter 
 -dDriveHUD.Inserter.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Inserter\DriveHUD.Inserter.csproj 
 -dDriveHUD.Inserter.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Inserter\bin\Release\ 
 -dDriveHUD.Inserter.TargetExt=.dll 
 -dDriveHUD.Inserter.TargetFileName=DriveHUD.Inserter.dll 
 -dDriveHUD.Inserter.TargetName=DriveHUD.Inserter 
 -dDriveHUD.Inserter.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Inserter\bin\Release\DriveHUD.Inserter.dll 
 -dDriveHUD.Updater.Core.Configuration=Release -d"DriveHUD.Updater.Core.FullConfiguration=Release|AnyCPU" 
 -dDriveHUD.Updater.Core.Platform=AnyCPU 
 -dDriveHUD.Updater.Core.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Updater.Core\ 
 -dDriveHUD.Updater.Core.ProjectExt=.csproj 
 -dDriveHUD.Updater.Core.ProjectFileName=DriveHUD.Updater.Core.csproj 
 -dDriveHUD.Updater.Core.ProjectName=DriveHUD.Updater.Core 
 -dDriveHUD.Updater.Core.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Updater.Core\DriveHUD.Updater.Core.csproj 
 -dDriveHUD.Updater.Core.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Updater.Core\bin\Release\ 
 -dDriveHUD.Updater.Core.TargetExt=.dll -dDriveHUD.Updater.Core.TargetFileName=DriveHUD.Updater.Core.dll -dDriveHUD.Updater.Core.TargetName=DriveHUD.Updater.Core -dDriveHUD.Updater.Core.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Updater.Core\bin\Release\DriveHUD.Updater.Core.dll -dDriveHUD.Updater.Configuration=Release -d"DriveHUD.Updater.FullConfiguration=Release|AnyCPU" -dDriveHUD.Updater.Platform=AnyCPU -dDriveHUD.Updater.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Updater\ -dDriveHUD.Updater.ProjectExt=.csproj -dDriveHUD.Updater.ProjectFileName=DriveHUD.Updater.csproj -dDriveHUD.Updater.ProjectName=DriveHUD.Updater -dDriveHUD.Updater.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Updater\DriveHUD.Updater.csproj -dDriveHUD.Updater.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Application\bin\Release\ -dDriveHUD.Updater.TargetExt=.exe -dDriveHUD.Updater.TargetFileName=DriveHUD.Updater.exe -dDriveHUD.Updater.TargetName=DriveHUD.Updater -dDriveHUD.Updater.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Application\bin\Release\DriveHUD.Updater.exe -dDriveHUD.ViewModels.Configuration=Release -d"DriveHUD.ViewModels.FullConfiguration=Release|AnyCPU" -dDriveHUD.ViewModels.Platform=AnyCPU -dDriveHUD.ViewModels.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.ViewModels\ -dDriveHUD.ViewModels.ProjectExt=.csproj -dDriveHUD.ViewModels.ProjectFileName=DriveHUD.ViewModels.csproj -dDriveHUD.ViewModels.ProjectName=DriveHUD.ViewModels -dDriveHUD.ViewModels.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.ViewModels\DriveHUD.ViewModels.csproj -dDriveHUD.ViewModels.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.ViewModels\bin\Release\ -dDriveHUD.ViewModels.TargetExt=.dll -dDriveHUD.ViewModels.TargetFileName=DriveHUD.ViewModels.dll -dDriveHUD.ViewModels.TargetName=DriveHUD.ViewModels -dDriveHUD.ViewModels.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.ViewModels\bin\Release\DriveHUD.ViewModels.dll -dModel.Configuration=Release -d"Model.FullConfiguration=Release|AnyCPU" -dModel.Platform=AnyCPU -dModel.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\Model\ -dModel.ProjectExt=.csproj -dModel.ProjectFileName=Model.csproj -dModel.ProjectName=Model -dModel.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\Model\Model.csproj -dModel.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\Model\bin\Release\ -dModel.TargetExt=.dll -dModel.TargetFileName=Model.dll -dModel.TargetName=Model -dModel.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\Model\bin\Release\Model.dll -dHandHistories.Objects.Configuration=Release -d"HandHistories.Objects.FullConfiguration=Release|AnyCPU" -dHandHistories.Objects.Platform=AnyCPU -dHandHistories.Objects.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\PokerHandHistoryParser\HandHistories.Objects\ -dHandHistories.Objects.ProjectExt=.csproj -dHandHistories.Objects.ProjectFileName=HandHistories.Objects.csproj -dHandHistories.Objects.ProjectName=HandHistories.Objects -dHandHistories.Objects.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\PokerHandHistoryParser\HandHistories.Objects\HandHistories.Objects.csproj -dHandHistories.Objects.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\PokerHandHistoryParser\HandHistories.Objects\bin\Release\ -dHandHistories.Objects.TargetExt=.dll -dHandHistories.Objects.TargetFileName=HandHistories.Objects.dll -dHandHistories.Objects.TargetName=HandHistories.Objects -dHandHistories.Objects.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\PokerHandHistoryParser\HandHistories.Objects\bin\Release\HandHistories.Objects.dll -dHandHistories.Parser.Configuration=Release -d"HandHistories.Parser.FullConfiguration=Release|AnyCPU" -dHandHistories.Parser.Platform=AnyCPU -dHandHistories.Parser.ProjectDir=D:\AcePokerSolutions\DriveHUD\trunk\src\PokerHandHistoryParser\HandHistories.Parser\ -dHandHistories.Parser.ProjectExt=.csproj -dHandHistories.Parser.ProjectFileName=HandHistories.Parser.csproj -dHandHistories.Parser.ProjectName=HandHistories.Parser -dHandHistories.Parser.ProjectPath=D:\AcePokerSolutions\DriveHUD\trunk\src\PokerHandHistoryParser\HandHistories.Parser\HandHistories.Parser.csproj -dHandHistories.Parser.TargetDir=D:\AcePokerSolutions\DriveHUD\trunk\src\PokerHandHistoryParser\HandHistories.Parser\bin\Release\ -dHandHistories.Parser.TargetExt=.dll -dHandHistories.Parser.TargetFileName=HandHistories.Parser.dll -dHandHistories.Parser.TargetName=HandHistories.Parser -dHandHistories.Parser.TargetPath=D:\AcePokerSolutions\DriveHUD\trunk\src\PokerHandHistoryParser\HandHistories.Parser\bin\Release\HandHistories.Parser.dll -out obj\Release\ -arch x86 -ext ..\dependencies\Wix\WixUIExtension.dll -ext ..\dependencies\Wix\WixNetFxExtension.dll Product.wxs

"C:\Program Files (x86)\WiX Toolset v3.10\bin\Light.exe" -out D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Setup\bin\Release\DriveHUD.msi -pdbout D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Setup\bin\Release\DriveHUD.wixpdb -cultures:null -ext ..\dependencies\Wix\WixUIExtension.dll -ext ..\dependencies\Wix\WixNetFxExtension.dll -contentsfile obj\Release\DriveHUD.Setup.wixproj.BindContentsFileListnull.txt -outputsfile obj\Release\DriveHUD.Setup.wixproj.BindOutputsFileListnull.txt -builtoutputsfile obj\Release\DriveHUD.Setup.wixproj.BindBuiltOutputsFileListnull.txt -wixprojectfile D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Setup\DriveHUD.Setup.wixproj obj\Release\Product.wixobj

"C:\Program Files (x86)\WiX Toolset v3.10\bin\Light.exe" -out D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Bootstrapper\bin\Release\DriveHUD-install.exe -pdbout D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Bootstrapper\bin\Release\DriveHUD-install.wixpdb -ext ..\dependencies\Wix\WixNetFxExtension.dll -ext ..\dependencies\Wix\WixBalExtension.dll -ext ..\dependencies\Wix\WixUtilExtension.dll -contentsfile obj\Release\DriveHUD.Bootstrapper.wixproj.BindContentsFileList.txt -outputsfile obj\Release\DriveHUD.Bootstrapper.wixproj.BindOutputsFileList.txt -builtoutputsfile obj\Release\DriveHUD.Bootstrapper.wixproj.BindBuiltOutputsFileList.txt -wixprojectfile D:\AcePokerSolutions\DriveHUD\trunk\src\DriveHUD.Bootstrapper\DriveHUD.Bootstrapper.wixproj obj\Release\Bundle.wixobj


-dSolutionDir=D:\Git\DriveHUD\ 
-dSolutionExt=.sln 
-dSolutionFileName=DriveHUD.sln 
-dSolutionName=DriveHUD 
-dSolutionPath=D:\Git\DriveHUD\DriveHUD.sln 
-dConfiguration=Release 
-dOutDir=bin\Release\ 
-dPlatform=x86 
-dProjectDir=d:\Git\DriveHUD\DriveHUD.Setup\ 
-dProjectExt=.wixproj 
-dProjectFileName=DriveHUD.Setup.wixproj 
-dProjectName=DriveHUD.Setup 
-dProjectPath=d:\Git\DriveHUD\DriveHUD.Setup\DriveHUD.Setup.wixproj 
-dTargetDir=d:\Git\DriveHUD\DriveHUD.Setup\bin\Release\ 
-dTargetExt=.msi 
-dTargetFileName=DriveHUD.msi 
-dTargetName=DriveHUD 
-dTargetPath=d:\Git\DriveHUD\DriveHUD.Setup\bin\Release\DriveHUD.msi 
-out obj\Release\ 
-arch x86 
-ext ..\dependencies\Wix\WixUIExtension.dll 
-ext ..\dependencies\Wix\WixNetFxExtension.dll 
Product.wxs
