using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DriveHUD.PlayerXRay.DataTypes
{
    public static class HoleCardsHelper
    {
        public static int ConverterCardsToSuitedUnsuited(string cards)
        {
            if (cards.Length != 4)
                return -1;

            if (cards[1] == cards[3])
                return GetHoleCardValue("" + cards[0] + cards[2] + "s");

            if (cards[1] != cards[3])
                return GetHoleCardValue("" + cards[0] + cards[2] + "o");

            return -1;
        }


        public static string GetHoleCard(int val)
        {
            switch (val)
            {
                case 1:
                return "AA";
                case 2:
                return "KK";
                case 3:
                return "QQ";
                case 4:
                return "JJ";
                case 5:
                return "TT";
                case 6:
                return "99";
                case 7:
                return "88";
                case 8:
                return "77";
                case 9:
                return "66";
                case 10:
                return "55";
                case 11:
                return "44";
                case 12:
                return "33";
                case 13:
                return "22";
                case 14:
                return "AKs";
                case 15:
                return "AQs";
                case 16:
                return "AJs";
                case 17:
                return "ATs";
                case 18:
                return "A9s";
                case 19:
                return "A8s";
                case 20:
                return "A7s";
                case 21:
                return "A6s";
                case 22:
                return "A5s";
                case 23:
                return "A4s";
                case 24:
                return "A3s";
                case 25:
                return "A2s";
                case 26:
                return "KQs";
                case 27:
                return "KJs";
                case 28:
                return "KTs";
                case 29:
                return "K9s";
                case 30:
                return "K8s";
                case 31:
                return "K7s";
                case 32:
                return "K6s";
                case 33:
                return "K5s";
                case 34:
                return "K4s";
                case 35:
                return "K3s";
                case 36:
                return "K2s";
                case 37:
                return "QJs";
                case 38:
                return "QTs";
                case 39:
                return "Q9s";
                case 40:
                return "Q8s";
                case 41:
                return "Q7s";
                case 42:
                return "Q6s";
                case 43:
                return "Q5s";
                case 44:
                return "Q4s";
                case 45:
                return "Q3s";
                case 46:
                return "Q2s";
                case 47:
                return "JTs";
                case 48:
                return "J9s";
                case 49:
                return "J8s";
                case 50:
                return "J7s";
                case 51:
                return "J6s";
                case 52:
                return "J5s";
                case 53:
                return "J4s";
                case 54:
                return "J3s";
                case 55:
                return "J2s";
                case 56:
                return "T9s";
                case 57:
                return "T8s";
                case 58:
                return "T7s";
                case 59:
                return "T6s";
                case 60:
                return "T5s";
                case 61:
                return "T4s";
                case 62:
                return "T3s";
                case 63:
                return "T2s";
                case 64:
                return "98s";
                case 65:
                return "97s";
                case 66:
                return "96s";
                case 67:
                return "95s";
                case 68:
                return "94s";
                case 69:
                return "93s";
                case 70:
                return "92s";
                case 71:
                return "87s";
                case 72:
                return "86s";
                case 73:
                return "85s";
                case 74:
                return "84s";
                case 75:
                return "83s";
                case 76:
                return "82s";
                case 77:
                return "76s";
                case 78:
                return "75s";
                case 79:
                return "74s";
                case 80:
                return "73s";
                case 81:
                return "72s";
                case 82:
                return "65s";
                case 83:
                return "64s";
                case 84:
                return "63s";
                case 85:
                return "62s";
                case 86:
                return "54s";
                case 87:
                return "53s";
                case 88:
                return "52s";
                case 89:
                return "43s";
                case 90:
                return "42s";
                case 91:
                return "32s";
                case 92:
                return "AKo";
                case 93:
                return "AQo";
                case 94:
                return "AJo";
                case 95:
                return "ATo";
                case 96:
                return "A9o";
                case 97:
                return "A8o";
                case 98:
                return "A7o";
                case 99:
                return "A6o";
                case 100:
                return "A5o";
                case 101:
                return "A4o";
                case 102:
                return "A3o";
                case 103:
                return "A2o";
                case 104:
                return "KQo";
                case 105:
                return "KJo";
                case 106:
                return "KTo";
                case 107:
                return "K9o";
                case 108:
                return "K8o";
                case 109:
                return "K7o";
                case 110:
                return "K6o";
                case 111:
                return "K5o";
                case 112:
                return "K4o";
                case 113:
                return "K3o";
                case 114:
                return "K2o";
                case 115:
                return "QJo";
                case 116:
                return "QTo";
                case 117:
                return "Q9o";
                case 118:
                return "Q8o";
                case 119:
                return "Q7o";
                case 120:
                return "Q6o";
                case 121:
                return "Q5o";
                case 122:
                return "Q4o";
                case 123:
                return "Q3o";
                case 124:
                return "Q2o";
                case 125:
                return "JTo";
                case 126:
                return "J9o";
                case 127:
                return "J8o";
                case 128:
                return "J7o";
                case 129:
                return "J6o";
                case 130:
                return "J5o";
                case 131:
                return "J4o";
                case 132:
                return "J3o";
                case 133:
                return "J2o";
                case 134:
                return "T9o";
                case 135:
                return "T8o";
                case 136:
                return "T7o";
                case 137:
                return "T6o";
                case 138:
                return "T5o";
                case 139:
                return "T4o";
                case 140:
                return "T3o";
                case 141:
                return "T2o";
                case 142:
                return "98o";
                case 143:
                return "97o";
                case 144:
                return "96o";
                case 145:
                return "95o";
                case 146:
                return "94o";
                case 147:
                return "93o";
                case 148:
                return "92o";
                case 149:
                return "87o";
                case 150:
                return "86o";
                case 151:
                return "85o";
                case 152:
                return "84o";
                case 153:
                return "83o";
                case 154:
                return "82o";
                case 155:
                return "76o";
                case 156:
                return "75o";
                case 157:
                return "74o";
                case 158:
                return "73o";
                case 159:
                return "72o";
                case 160:
                return "65o";
                case 161:
                return "64o";
                case 162:
                return "63o";
                case 163:
                return "62o";
                case 164:
                return "54o";
                case 165:
                return "53o";
                case 166:
                return "52o";
                case 167:
                return "43o";
                case 168:
                return "42o";
                case 169:
                return "32o";
            }
            return "";
        }

        public static int GetHoleCardValue(string card)
        {
            switch (card)
            {
                case "AA":
                    return 1;
                case "KK":
                    return 2;
                case "QQ":
                    return 3;
                case "JJ":
                    return 4;
                case "TT":
                    return 5;
                case "99":
                    return 6;
                case "88":
                    return 7;
                case "77":
                    return 8;
                case "66":
                    return 9;
                case "55":
                    return 10;
                case "44":
                    return 11;
                case "33":
                    return 12;
                case "22":
                    return 13;
                case "AKs":
                    return 14;
                case "AQs":
                    return 15;
                case "AJs":
                    return 16;
                case "ATs":
                    return 17;
                case "A9s":
                    return 18;
                case "A8s":
                    return 19;
                case "A7s":
                    return 20;
                case "A6s":
                    return 21;
                case "A5s":
                    return 22;
                case "A4s":
                    return 23;
                case "A3s":
                    return 24;
                case "A2s":
                    return 25;
                case "KQs":
                    return 26;
                case "KJs":
                    return 27;
                case "KTs":
                    return 28;
                case "K9s":
                    return 29;
                case "K8s":
                    return 30;
                case "K7s":
                    return 31;
                case "K6s":
                    return 32;
                case "K5s":
                    return 33;
                case "K4s":
                    return 34;
                case "K3s":
                    return 35;
                case "K2s":
                    return 36;
                case "QJs":
                    return 37;
                case "QTs":
                    return 38;
                case "Q9s":
                    return 39;
                case "Q8s":
                    return 40;
                case "Q7s":
                    return 41;
                case "Q6s":
                    return 42;
                case "Q5s":
                    return 43;
                case "Q4s":
                    return 44;
                case "Q3s":
                    return 45;
                case "Q2s":
                    return 46;
                case "JTs":
                    return 47;
                case "J9s":
                    return 48;
                case "J8s":
                    return 49;
                case "J7s":
                    return 50;
                case "J6s":
                    return 51;
                case "J5s":
                    return 52;
                case "J4s":
                    return 53;
                case "J3s":
                    return 54;
                case "J2s":
                    return 55;
                case "T9s":
                    return 56;
                case "T8s":
                    return 57;
                case "T7s":
                    return 58;
                case "T6s":
                    return 59;
                case "T5s":
                    return 60;
                case "T4s":
                    return 61;
                case "T3s":
                    return 62;
                case "T2s":
                    return 63;
                case "98s":
                    return 64;
                case "97s":
                    return 65;
                case "96s":
                    return 66;
                case "95s":
                    return 67;
                case "94s":
                    return 68;
                case "93s":
                    return 69;
                case "92s":
                    return 70;
                case "87s":
                    return 71;
                case "86s":
                    return 72;
                case "85s":
                    return 73;
                case "84s":
                    return 74;
                case "83s":
                    return 75;
                case "82s":
                    return 76;
                case "76s":
                    return 77;
                case "75s":
                    return 78;
                case "74s":
                    return 79;
                case "73s":
                    return 80;
                case "72s":
                    return 81;
                case "65s":
                    return 82;
                case "64s":
                    return 83;
                case "63s":
                    return 84;
                case "62s":
                    return 85;
                case "54s":
                    return 86;
                case "53s":
                    return 87;
                case "52s":
                    return 88;
                case "43s":
                    return 89;
                case "42s":
                    return 90;
                case "32s":
                    return 91;
                case "AKo":
                    return 92;
                case "AQo":
                    return 93;
                case "AJo":
                    return 94;
                case "ATo":
                    return 95;
                case "A9o":
                    return 96;
                case "A8o":
                    return 97;
                case "A7o":
                    return 98;
                case "A6o":
                    return 99;
                case "A5o":
                    return 100;
                case "A4o":
                    return 101;
                case "A3o":
                    return 102;
                case "A2o":
                    return 103;
                case "KQo":
                    return 104;
                case "KJo":
                    return 105;
                case "KTo":
                    return 106;
                case "K9o":
                    return 107;
                case "K8o":
                    return 108;
                case "K7o":
                    return 109;
                case "K6o":
                    return 110;
                case "K5o":
                    return 111;
                case "K4o":
                    return 112;
                case "K3o":
                    return 113;
                case "K2o":
                    return 114;
                case "QJo":
                    return 115;
                case "QTo":
                    return 116;
                case "Q9o":
                    return 117;
                case "Q8o":
                    return 118;
                case "Q7o":
                    return 119;
                case "Q6o":
                    return 120;
                case "Q5o":
                    return 121;
                case "Q4o":
                    return 122;
                case "Q3o":
                    return 123;
                case "Q2o":
                    return 124;
                case "JTo":
                    return 125;
                case "J9o":
                    return 126;
                case "J8o":
                    return 127;
                case "J7o":
                    return 128;
                case "J6o":
                    return 129;
                case "J5o":
                    return 130;
                case "J4o":
                    return 131;
                case "J3o":
                    return 132;
                case "J2o":
                    return 133;
                case "T9o":
                    return 134;
                case "T8o":
                    return 135;
                case "T7o":
                    return 136;
                case "T6o":
                    return 137;
                case "T5o":
                    return 138;
                case "T4o":
                    return 139;
                case "T3o":
                    return 140;
                case "T2o":
                    return 141;
                case "98o":
                    return 142;
                case "97o":
                    return 143;
                case "96o":
                    return 144;
                case "95o":
                    return 145;
                case "94o":
                    return 146;
                case "93o":
                    return 147;
                case "92o":
                    return 148;
                case "87o":
                    return 149;
                case "86o":
                    return 150;
                case "85o":
                    return 151;
                case "84o":
                    return 152;
                case "83o":
                    return 153;
                case "82o":
                    return 154;
                case "76o":
                    return 155;
                case "75o":
                    return 156;
                case "74o":
                    return 157;
                case "73o":
                    return 158;
                case "72o":
                    return 159;
                case "65o":
                    return 160;
                case "64o":
                    return 161;
                case "63o":
                    return 162;
                case "62o":
                    return 163;
                case "54o":
                    return 164;
                case "53o":
                    return 165;
                case "52o":
                    return 166;
                case "43o":
                    return 167;
                case "42o":
                    return 168;
                case "32o":
                    return 169;
            }
            return 0;
        }
    }
}
